import { createContext, useContext } from 'react';

export const translations = {
  en: {
    languageName: 'English',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Enter your credentials to access your Meditrack dashboard.',
    phoneNumber: 'Phone Number',
    password: 'Password',
    enterPassword: 'Enter your password',
    signIn: 'Sign In Securely',
    signingIn: 'Signing In...',
    noAccount: "Don't have an account?",
    signupHere: 'Sign up here',
    demoShortcuts: 'Demo login shortcuts',
    createAccount: 'Create Account',
    joinNetwork: 'Join the Network',
    registerCopy: 'Create your account to manage livestock health, prescriptions, AI adherence insights, and antimicrobial usage data.',
    fullName: 'Full Name',
    city: 'City/District',
    role: 'Select Role',
    createMeditrackAccount: 'Create Meditrack Account',
    creatingAccount: 'Creating Account...',
    alreadyAccount: 'Already have an account?',
    loginHere: 'Log in here',
    adminControlCenter: 'Admin Control Center',
    meditrackIntelligence: 'Meditrack Intelligence',
    aiSurveillance: 'AI powered AMU surveillance',
    adminHeroTitle: 'Real-time medicine safety, adherence risk, and regional prescription intelligence.',
    adminHeroCopy: 'Review antimicrobial usage, identify high-volume regions, and monitor AI-generated adherence signals before risk becomes critical.',
    currentRegion: 'Current Region',
    records: 'Records',
    coverage: 'Coverage',
    totalAmuRecords: 'Total AMU Records',
    activeRegions: 'Active Regions',
    medicinesTracked: 'Medicines Tracked',
    signOut: 'Sign Out',
    farmerCare: 'Meditrack Farmer Care',
    pharmacy: 'Meditrack Pharmacy',
    registrar: 'Meditrack Registrar',
    vetConsole: 'Meditrack Vet Console',
    aiReport: 'System Health and Adherence Intelligence',
  },
  hi: {
    languageName: 'हिन्दी',
    theme: 'थीम',
    light: 'लाइट',
    dark: 'डार्क',
    language: 'भाषा',
    loginTitle: 'वापसी पर स्वागत है',
    loginSubtitle: 'अपने Meditrack डैशबोर्ड में जाने के लिए विवरण दर्ज करें।',
    phoneNumber: 'फोन नंबर',
    password: 'पासवर्ड',
    enterPassword: 'अपना पासवर्ड दर्ज करें',
    signIn: 'सुरक्षित साइन इन',
    signingIn: 'साइन इन हो रहा है...',
    noAccount: 'खाता नहीं है?',
    signupHere: 'यहां साइन अप करें',
    demoShortcuts: 'डेमो लॉगिन शॉर्टकट',
    createAccount: 'खाता बनाएं',
    joinNetwork: 'नेटवर्क से जुड़ें',
    registerCopy: 'पशु स्वास्थ्य, प्रिस्क्रिप्शन, AI पालन रिपोर्ट और AMU डेटा प्रबंधित करने के लिए खाता बनाएं।',
    fullName: 'पूरा नाम',
    city: 'शहर/जिला',
    role: 'भूमिका चुनें',
    createMeditrackAccount: 'Meditrack खाता बनाएं',
    creatingAccount: 'खाता बन रहा है...',
    alreadyAccount: 'पहले से खाता है?',
    loginHere: 'यहां लॉग इन करें',
    adminControlCenter: 'एडमिन कंट्रोल सेंटर',
    meditrackIntelligence: 'Meditrack इंटेलिजेंस',
    aiSurveillance: 'AI आधारित AMU निगरानी',
    adminHeroTitle: 'रीयल-टाइम दवा सुरक्षा, पालन जोखिम और क्षेत्रीय प्रिस्क्रिप्शन जानकारी।',
    adminHeroCopy: 'AMU उपयोग देखें, अधिक उपयोग वाले क्षेत्रों को पहचानें, और जोखिम बढ़ने से पहले AI संकेतों की निगरानी करें।',
    currentRegion: 'वर्तमान क्षेत्र',
    records: 'रिकॉर्ड',
    coverage: 'कवरेज',
    totalAmuRecords: 'कुल AMU रिकॉर्ड',
    activeRegions: 'सक्रिय क्षेत्र',
    medicinesTracked: 'ट्रैक की गई दवाएं',
    signOut: 'साइन आउट',
    farmerCare: 'Meditrack किसान देखभाल',
    pharmacy: 'Meditrack फार्मेसी',
    registrar: 'Meditrack रजिस्ट्रार',
    vetConsole: 'Meditrack पशु चिकित्सक कंसोल',
    aiReport: 'सिस्टम स्वास्थ्य और पालन इंटेलिजेंस',
  },
  mr: {
    languageName: 'मराठी',
    theme: 'थीम',
    light: 'लाइट',
    dark: 'डार्क',
    language: 'भाषा',
    loginTitle: 'परत स्वागत आहे',
    loginSubtitle: 'Meditrack डॅशबोर्ड वापरण्यासाठी आपली माहिती भरा.',
    phoneNumber: 'फोन नंबर',
    password: 'पासवर्ड',
    enterPassword: 'पासवर्ड टाका',
    signIn: 'सुरक्षित साइन इन',
    signingIn: 'साइन इन होत आहे...',
    noAccount: 'खाते नाही?',
    signupHere: 'इथे साइन अप करा',
    demoShortcuts: 'डेमो लॉगिन शॉर्टकट',
    createAccount: 'खाते तयार करा',
    joinNetwork: 'नेटवर्कमध्ये सामील व्हा',
    registerCopy: 'पशुधन आरोग्य, प्रिस्क्रिप्शन, AI पालन माहिती आणि AMU डेटा व्यवस्थापित करण्यासाठी खाते तयार करा.',
    fullName: 'पूर्ण नाव',
    city: 'शहर/जिल्हा',
    role: 'भूमिका निवडा',
    createMeditrackAccount: 'Meditrack खाते तयार करा',
    creatingAccount: 'खाते तयार होत आहे...',
    alreadyAccount: 'आधीच खाते आहे?',
    loginHere: 'इथे लॉग इन करा',
    adminControlCenter: 'अॅडमिन कंट्रोल सेंटर',
    meditrackIntelligence: 'Meditrack इंटेलिजन्स',
    aiSurveillance: 'AI आधारित AMU निरीक्षण',
    adminHeroTitle: 'रीयल-टाइम औषध सुरक्षा, पालन जोखीम आणि प्रादेशिक प्रिस्क्रिप्शन माहिती.',
    adminHeroCopy: 'AMU वापर तपासा, जास्त वापर असलेले भाग ओळखा, आणि धोका वाढण्यापूर्वी AI संकेत पाहा.',
    currentRegion: 'सध्याचा प्रदेश',
    records: 'रेकॉर्ड',
    coverage: 'कव्हरेज',
    totalAmuRecords: 'एकूण AMU रेकॉर्ड',
    activeRegions: 'सक्रिय प्रदेश',
    medicinesTracked: 'ट्रॅक केलेली औषधे',
    signOut: 'साइन आउट',
    farmerCare: 'Meditrack शेतकरी सेवा',
    pharmacy: 'Meditrack फार्मसी',
    registrar: 'Meditrack रजिस्ट्रार',
    vetConsole: 'Meditrack पशुवैद्य कन्सोल',
    aiReport: 'सिस्टम आरोग्य आणि पालन इंटेलिजन्स',
  },
  gu: {
    languageName: 'ગુજરાતી',
    theme: 'થીમ',
    light: 'લાઇટ',
    dark: 'ડાર્ક',
    language: 'ભાષા',
    loginTitle: 'ફરીથી સ્વાગત છે',
    loginSubtitle: 'તમારા Meditrack ડેશબોર્ડ માટે વિગતો દાખલ કરો.',
    phoneNumber: 'ફોન નંબર',
    password: 'પાસવર્ડ',
    enterPassword: 'પાસવર્ડ દાખલ કરો',
    signIn: 'સુરક્ષિત સાઇન ઇન',
    signingIn: 'સાઇન ઇન થઈ રહ્યું છે...',
    noAccount: 'ખાતું નથી?',
    signupHere: 'અહીં સાઇન અપ કરો',
    demoShortcuts: 'ડેમો લોગિન શોર્ટકટ',
    createAccount: 'ખાતું બનાવો',
    joinNetwork: 'નેટવર્કમાં જોડાઓ',
    registerCopy: 'પશુ આરોગ્ય, પ્રિસ્ક્રિપ્શન, AI પાલન માહિતી અને AMU ડેટા માટે ખાતું બનાવો.',
    fullName: 'પૂરું નામ',
    city: 'શહેર/જિલ્લો',
    role: 'ભૂમિકા પસંદ કરો',
    createMeditrackAccount: 'Meditrack ખાતું બનાવો',
    creatingAccount: 'ખાતું બની રહ્યું છે...',
    alreadyAccount: 'પહેલેથી ખાતું છે?',
    loginHere: 'અહીં લોગિન કરો',
    adminControlCenter: 'એડમિન કંટ્રોલ સેન્ટર',
    meditrackIntelligence: 'Meditrack ઇન્ટેલિજન્સ',
    aiSurveillance: 'AI આધારિત AMU દેખરેખ',
    adminHeroTitle: 'રીયલ-ટાઇમ દવા સુરક્ષા, પાલન જોખમ અને પ્રાદેશિક પ્રિસ્ક્રિપ્શન માહિતી.',
    adminHeroCopy: 'AMU ઉપયોગ જુઓ, ઉચ્ચ ઉપયોગવાળા વિસ્તારો ઓળખો અને જોખમ વધે તે પહેલાં AI સંકેતો પર નજર રાખો.',
    currentRegion: 'વર્તમાન વિસ્તાર',
    records: 'રેકોર્ડ',
    coverage: 'કવરેજ',
    totalAmuRecords: 'કુલ AMU રેકોર્ડ',
    activeRegions: 'સક્રિય વિસ્તાર',
    medicinesTracked: 'ટ્રેક કરેલી દવાઓ',
    signOut: 'સાઇન આઉટ',
    farmerCare: 'Meditrack ખેડૂત સેવા',
    pharmacy: 'Meditrack ફાર્મસી',
    registrar: 'Meditrack રજીસ્ટ્રાર',
    vetConsole: 'Meditrack વેટ કન્સોલ',
    aiReport: 'સિસ્ટમ આરોગ્ય અને પાલન ઇન્ટેલિજન્સ',
  },
  ta: {
    languageName: 'தமிழ்',
    theme: 'தீம்',
    light: 'லைட்',
    dark: 'டார்க்',
    language: 'மொழி',
    loginTitle: 'மீண்டும் வரவேற்கிறோம்',
    loginSubtitle: 'உங்கள் Meditrack டாஷ்போர்டுக்கு விவரங்களை உள்ளிடவும்.',
    phoneNumber: 'தொலைபேசி எண்',
    password: 'கடவுச்சொல்',
    enterPassword: 'கடவுச்சொல்லை உள்ளிடவும்',
    signIn: 'பாதுகாப்பாக உள்நுழையவும்',
    signingIn: 'உள்நுழைகிறது...',
    noAccount: 'கணக்கு இல்லையா?',
    signupHere: 'இங்கே பதிவு செய்யவும்',
    demoShortcuts: 'டெமோ உள்நுழைவு',
    createAccount: 'கணக்கு உருவாக்கு',
    joinNetwork: 'நெட்வொர்க்கில் சேரவும்',
    registerCopy: 'கால்நடை ஆரோக்கியம், மருந்து சீட்டு, AI பின்பற்றல் தகவல் மற்றும் AMU தரவை நிர்வகிக்க கணக்கு உருவாக்கவும்.',
    fullName: 'முழு பெயர்',
    city: 'நகரம்/மாவட்டம்',
    role: 'பங்கு தேர்வு',
    createMeditrackAccount: 'Meditrack கணக்கு உருவாக்கு',
    creatingAccount: 'கணக்கு உருவாகிறது...',
    alreadyAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    loginHere: 'இங்கே உள்நுழைக',
    adminControlCenter: 'நிர்வாக கட்டுப்பாட்டு மையம்',
    meditrackIntelligence: 'Meditrack நுண்ணறிவு',
    aiSurveillance: 'AI அடிப்படையிலான AMU கண்காணிப்பு',
    adminHeroTitle: 'நேரடி மருந்து பாதுகாப்பு, பின்பற்றல் அபாயம் மற்றும் பிராந்திய மருந்து தகவல்.',
    adminHeroCopy: 'AMU பயன்பாட்டை பரிசீலிக்கவும், அதிக பயன்பாட்டு பகுதிகளை அடையாளம் காணவும், அபாயம் அதிகரிக்கும் முன் AI சிக்னல்களை கண்காணிக்கவும்.',
    currentRegion: 'தற்போதைய பகுதி',
    records: 'பதிவுகள்',
    coverage: 'கவரேஜ்',
    totalAmuRecords: 'மொத்த AMU பதிவுகள்',
    activeRegions: 'செயலில் உள்ள பகுதிகள்',
    medicinesTracked: 'கண்காணிக்கப்படும் மருந்துகள்',
    signOut: 'வெளியேறு',
    farmerCare: 'Meditrack விவசாயி பராமரிப்பு',
    pharmacy: 'Meditrack மருந்தகம்',
    registrar: 'Meditrack பதிவாளர்',
    vetConsole: 'Meditrack கால்நடை மருத்துவர் கன்சோல்',
    aiReport: 'சிஸ்டம் ஆரோக்கியம் மற்றும் பின்பற்றல் நுண்ணறிவு',
  },
};

export const languageOptions = Object.entries(translations).map(([code, values]) => ({
  code,
  label: values.languageName,
}));

export const AppSettingsContext = createContext(null);

export const useAppSettings = () => {
  const context = useContext(AppSettingsContext);
  if (!context) {
    throw new Error('useAppSettings must be used inside AppSettingsProvider');
  }
  return context;
};
