/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    languageName: 'English',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Enter your credentials to access your Meditrack dashboard.',
    phoneNumber: 'Phone Number',
    password: 'Password',
    enterPassword: 'Enter your password',
    signIn: 'Sign In Securely',
    signingIn: 'Signing In...',
    noAccount: "Don't have an account?",
    signupHere: 'Sign up here',
    demoShortcuts: 'Demo login shortcuts',
    createAccount: 'Create Account',
    joinNetwork: 'Join the Network',
    registerCopy: 'Create your account to manage livestock health, prescriptions, AI adherence insights, and antimicrobial usage data.',
    fullName: 'Full Name',
    city: 'City/District',
    role: 'Select Role',
    createMeditrackAccount: 'Create Meditrack Account',
    creatingAccount: 'Creating Account...',
    alreadyAccount: 'Already have an account?',
    loginHere: 'Log in here',
    adminControlCenter: 'Admin Control Center',
    meditrackIntelligence: 'Meditrack Intelligence',
    aiSurveillance: 'AI powered AMU surveillance',
    adminHeroTitle: 'Real-time medicine safety, adherence risk, and regional prescription intelligence.',
    adminHeroCopy: 'Review antimicrobial usage, identify high-volume regions, and monitor AI-generated adherence signals before risk becomes critical.',
    currentRegion: 'Current Region',
    records: 'Records',
    coverage: 'Coverage',
    totalAmuRecords: 'Total AMU Records',
    activeRegions: 'Active Regions',
    medicinesTracked: 'Medicines Tracked',
    signOut: 'Sign Out',
    farmerCare: 'Meditrack Farmer Care',
    pharmacy: 'Meditrack Pharmacy',
    registrar: 'Meditrack Registrar',
    vetConsole: 'Meditrack Vet Console',
    aiReport: 'System Health and Adherence Intelligence',
  },
  hi: {
    languageName: 'हिन्दी',
    theme: 'थीम',
    light: 'लाइट',
    dark: 'डार्क',
    language: 'भाषा',
    loginTitle: 'वापसी पर स्वागत है',
    loginSubtitle: 'अपने Meditrack डैशबोर्ड में जाने के लिए विवरण दर्ज करें।',
    phoneNumber: 'फोन नंबर',
    password: 'पासवर्ड',
    enterPassword: 'अपना पासवर्ड दर्ज करें',
    signIn: 'सुरक्षित साइन इन',
    signingIn: 'साइन इन हो रहा है...',
    noAccount: 'खाता नहीं है?',
    signupHere: 'यहां साइन अप करें',
    demoShortcuts: 'डेमो लॉगिन शॉर्टकट',
    createAccount: 'खाता बनाएं',
    joinNetwork: 'नेटवर्क से जुड़ें',
    registerCopy: 'पशु स्वास्थ्य, प्रिस्क्रिप्शन, AI पालन रिपोर्ट और AMU डेटा प्रबंधित करने के लिए खाता बनाएं।',
    fullName: 'पूरा नाम',
    city: 'शहर/जिला',
    role: 'भूमिका चुनें',
    createMeditrackAccount: 'Meditrack खाता बनाएं',
    creatingAccount: 'खाता बन रहा है...',
    alreadyAccount: 'पहले से खाता है?',
    loginHere: 'यहां लॉग इन करें',
    adminControlCenter: 'एडमिन कंट्रोल सेंटर',
    meditrackIntelligence: 'Meditrack इंटेलिजेंस',
    aiSurveillance: 'AI आधारित AMU निगरानी',
    adminHeroTitle: 'रीयल-टाइम दवा सुरक्षा, पालन जोखिम और क्षेत्रीय प्रिस्क्रिप्शन जानकारी।',
    adminHeroCopy: 'AMU उपयोग देखें, अधिक उपयोग वाले क्षेत्रों को पहचानें, और जोखिम बढ़ने से पहले AI संकेतों की निगरानी करें।',
    currentRegion: 'वर्तमान क्षेत्र',
    records: 'रिकॉर्ड',
    coverage: 'कवरेज',
    totalAmuRecords: 'कुल AMU रिकॉर्ड',
    activeRegions: 'सक्रिय क्षेत्र',
    medicinesTracked: 'ट्रैक की गई दवाएं',
    signOut: 'साइन आउट',
    farmerCare: 'Meditrack किसान देखभाल',
    pharmacy: 'Meditrack फार्मेसी',
    registrar: 'Meditrack रजिस्ट्रार',
    vetConsole: 'Meditrack पशु चिकित्सक कंसोल',
    aiReport: 'सिस्टम स्वास्थ्य और पालन इंटेलिजेंस',
  },
  mr: {
    languageName: 'मराठी',
    theme: 'थीम',
    light: 'लाइट',
    dark: 'डार्क',
    language: 'भाषा',
    loginTitle: 'परत स्वागत आहे',
    loginSubtitle: 'Meditrack डॅशबोर्ड वापरण्यासाठी आपली माहिती भरा.',
    phoneNumber: 'फोन नंबर',
    password: 'पासवर्ड',
    enterPassword: 'पासवर्ड टाका',
    signIn: 'सुरक्षित साइन इन',
    signingIn: 'साइन इन होत आहे...',
    noAccount: 'खाते नाही?',
    signupHere: 'इथे साइन अप करा',
    demoShortcuts: 'डेमो लॉगिन शॉर्टकट',
    createAccount: 'खाते तयार करा',
    joinNetwork: 'नेटवर्कमध्ये सामील व्हा',
    registerCopy: 'पशुधन आरोग्य, प्रिस्क्रिप्शन, AI पालन माहिती आणि AMU डेटा व्यवस्थापित करण्यासाठी खाते तयार करा.',
    fullName: 'पूर्ण नाव',
    city: 'शहर/जिल्हा',
    role: 'भूमिका निवडा',
    createMeditrackAccount: 'Meditrack खाते तयार करा',
    creatingAccount: 'खाते तयार होत आहे...',
    alreadyAccount: 'आधीच खाते आहे?',
    loginHere: 'इथे लॉग इन करा',
    adminControlCenter: 'अॅडमिन कंट्रोल सेंटर',
    meditrackIntelligence: 'Meditrack इंटेलिजन्स',
    aiSurveillance: 'AI आधारित AMU निरीक्षण',
    adminHeroTitle: 'रीयल-टाइम औषध सुरक्षा, पालन जोखीम आणि प्रादेशिक प्रिस्क्रिप्शन माहिती.',
    adminHeroCopy: 'AMU वापर तपासा, जास्त वापर असलेले भाग ओळखा, आणि धोका वाढण्यापूर्वी AI संकेत पाहा.',
    currentRegion: 'सध्याचा प्रदेश',
    records: 'रेकॉर्ड',
    coverage: 'कव्हरेज',
    totalAmuRecords: 'एकूण AMU रेकॉर्ड',
    activeRegions: 'सक्रिय प्रदेश',
    medicinesTracked: 'ट्रॅक केलेली औषधे',
    signOut: 'साइन आउट',
    farmerCare: 'Meditrack शेतकरी सेवा',
    pharmacy: 'Meditrack फार्मसी',
    registrar: 'Meditrack रजिस्ट्रार',
    vetConsole: 'Meditrack पशुवैद्य कन्सोल',
    aiReport: 'सिस्टम आरोग्य आणि पालन इंटेलिजन्स',
  },
  gu: {
    languageName: 'ગુજરાતી',
    theme: 'થીમ',
    light: 'લાઇટ',
    dark: 'ડાર્ક',
    language: 'ભાષા',
    loginTitle: 'ફરીથી સ્વાગત છે',
    loginSubtitle: 'તમારા Meditrack ડેશબોર્ડ માટે વિગતો દાખલ કરો.',
    phoneNumber: 'ફોન નંબર',
    password: 'પાસવર્ડ',
    enterPassword: 'પાસવર્ડ દાખલ કરો',
    signIn: 'સુરક્ષિત સાઇન ઇન',
    signingIn: 'સાઇન ઇન થઈ રહ્યું છે...',
    noAccount: 'ખાતું નથી?',
    signupHere: 'અહીં સાઇન અપ કરો',
    demoShortcuts: 'ડેમો લોગિન શોર્ટકટ',
    createAccount: 'ખાતું બનાવો',
    joinNetwork: 'નેટવર્કમાં જોડાઓ',
    registerCopy: 'પશુ આરોગ્ય, પ્રિસ્ક્રિપ્શન, AI પાલન માહિતી અને AMU ડેટા માટે ખાતું બનાવો.',
    fullName: 'પૂરું નામ',
    city: 'શહેર/જિલ્લો',
    role: 'ભૂમિકા પસંદ કરો',
    createMeditrackAccount: 'Meditrack ખાતું બનાવો',
    creatingAccount: 'ખાતું બની રહ્યું છે...',
    alreadyAccount: 'પહેલેથી ખાતું છે?',
    loginHere: 'અહીં લોગિન કરો',
    adminControlCenter: 'એડમિન કંટ્રોલ સેન્ટર',
    meditrackIntelligence: 'Meditrack ઇન્ટેલિજન્સ',
    aiSurveillance: 'AI આધારિત AMU દેખરેખ',
    adminHeroTitle: 'રીયલ-ટાઇમ દવા સુરક્ષા, પાલન જોખમ અને પ્રાદેશિક પ્રિસ્ક્રિપ્શન માહિતી.',
    adminHeroCopy: 'AMU ઉપયોગ જુઓ, ઉચ્ચ ઉપયોગવાળા વિસ્તારો ઓળખો અને જોખમ વધે તે પહેલાં AI સંકેતો પર નજર રાખો.',
    currentRegion: 'વર્તમાન વિસ્તાર',
    records: 'રેકોર્ડ',
    coverage: 'કવરેજ',
    totalAmuRecords: 'કુલ AMU રેકોર્ડ',
    activeRegions: 'સક્રિય વિસ્તાર',
    medicinesTracked: 'ટ્રેક કરેલી દવાઓ',
    signOut: 'સાઇન આઉટ',
    farmerCare: 'Meditrack ખેડૂત સેવા',
    pharmacy: 'Meditrack ફાર્મસી',
    registrar: 'Meditrack રજીસ્ટ્રાર',
    vetConsole: 'Meditrack વેટ કન્સોલ',
    aiReport: 'સિસ્ટમ આરોગ્ય અને પાલન ઇન્ટેલિજન્સ',
  },
  ta: {
    languageName: 'தமிழ்',
    theme: 'தீம்',
    light: 'லைட்',
    dark: 'டார்க்',
    language: 'மொழி',
    loginTitle: 'மீண்டும் வரவேற்கிறோம்',
    loginSubtitle: 'உங்கள் Meditrack டாஷ்போர்டுக்கு விவரங்களை உள்ளிடவும்.',
    phoneNumber: 'தொலைபேசி எண்',
    password: 'கடவுச்சொல்',
    enterPassword: 'கடவுச்சொல்லை உள்ளிடவும்',
    signIn: 'பாதுகாப்பாக உள்நுழையவும்',
    signingIn: 'உள்நுழைகிறது...',
    noAccount: 'கணக்கு இல்லையா?',
    signupHere: 'இங்கே பதிவு செய்யவும்',
    demoShortcuts: 'டெமோ உள்நுழைவு',
    createAccount: 'கணக்கு உருவாக்கு',
    joinNetwork: 'நெட்வொர்க்கில் சேரவும்',
    registerCopy: 'கால்நடை ஆரோக்கியம், மருந்து சீட்டு, AI பின்பற்றல் தகவல் மற்றும் AMU தரவை நிர்வகிக்க கணக்கு உருவாக்கவும்.',
    fullName: 'முழு பெயர்',
    city: 'நகரம்/மாவட்டம்',
    role: 'பங்கு தேர்வு',
    createMeditrackAccount: 'Meditrack கணக்கு உருவாக்கு',
    creatingAccount: 'கணக்கு உருவாகிறது...',
    alreadyAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    loginHere: 'இங்கே உள்நுழைக',
    adminControlCenter: 'நிர்வாக கட்டுப்பாட்டு மையம்',
    meditrackIntelligence: 'Meditrack நுண்ணறிவு',
    aiSurveillance: 'AI அடிப்படையிலான AMU கண்காணிப்பு',
    adminHeroTitle: 'நேரடி மருந்து பாதுகாப்பு, பின்பற்றல் அபாயம் மற்றும் பிராந்திய மருந்து தகவல்.',
    adminHeroCopy: 'AMU பயன்பாட்டை பரிசீலிக்கவும், அதிக பயன்பாட்டு பகுதிகளை அடையாளம் காணவும், அபாயம் அதிகரிக்கும் முன் AI சிக்னல்களை கண்காணிக்கவும்.',
    currentRegion: 'தற்போதைய பகுதி',
    records: 'பதிவுகள்',
    coverage: 'கவரேஜ்',
    totalAmuRecords: 'மொத்த AMU பதிவுகள்',
    activeRegions: 'செயலில் உள்ள பகுதிகள்',
    medicinesTracked: 'கண்காணிக்கப்படும் மருந்துகள்',
    signOut: 'வெளியேறு',
    farmerCare: 'Meditrack விவசாயி பராமரிப்பு',
    pharmacy: 'Meditrack மருந்தகம்',
    registrar: 'Meditrack பதிவாளர்',
    vetConsole: 'Meditrack கால்நடை மருத்துவர் கன்சோல்',
    aiReport: 'சிஸ்டம் ஆரோக்கியம் மற்றும் பின்பற்றல் நுண்ணறிவு',
  },
};

const farmerText = {
  en: {
    registeredFarmer: 'Registered Farmer',
    myMedicineAdherenceReport: 'My Medicine Adherence Report',
    askVetHelp: 'Ask for Vet Help',
    selectAnimal: 'Select Animal',
    chooseFromHerd: '-- Choose from your herd --',
    describeSymptoms: 'Describe Symptoms',
    symptomsPlaceholder: 'e.g., Stopped eating, high fever...',
    sendingAlert: 'Sending Alert...',
    submitRequest: 'Submit Request',
    treatmentRequestSuccess: 'Treatment request sent to nearby Vets!',
    treatmentRequestError: 'Error submitting request',
    treatmentHistory: 'My Treatment History',
    noTreatmentRecords: 'No treatment records found.',
    symptomsReported: 'Symptoms Reported',
    vetPrescription: 'Vet Prescription',
    withdrawal: 'Withdrawal',
    days: 'Days',
    statusPending: 'Pending',
    statusAccepted: 'Accepted',
    statusCompleted: 'Completed',
    statusRejected: 'Rejected',
  },
  hi: {
    registeredFarmer: 'पंजीकृत किसान',
    myMedicineAdherenceReport: 'मेरी दवा पालन रिपोर्ट',
    askVetHelp: 'पशु डॉक्टर से मदद लें',
    selectAnimal: 'पशु चुनें',
    chooseFromHerd: '-- अपने झुंड से चुनें --',
    describeSymptoms: 'लक्षण लिखें',
    symptomsPlaceholder: 'जैसे, खाना बंद, तेज बुखार...',
    sendingAlert: 'अलर्ट भेजा जा रहा है...',
    submitRequest: 'रिक्वेस्ट भेजें',
    treatmentRequestSuccess: 'उपचार रिक्वेस्ट पास के डॉक्टरों को भेज दी गई!',
    treatmentRequestError: 'रिक्वेस्ट भेजने में त्रुटि',
    treatmentHistory: 'मेरा उपचार इतिहास',
    noTreatmentRecords: 'कोई उपचार रिकॉर्ड नहीं मिला।',
    symptomsReported: 'बताए गए लक्षण',
    vetPrescription: 'पशु डॉक्टर की पर्ची',
    withdrawal: 'विथड्रॉअल',
    days: 'दिन',
    statusPending: 'लंबित',
    statusAccepted: 'स्वीकृत',
    statusCompleted: 'पूर्ण',
    statusRejected: 'अस्वीकृत',
  },
  mr: {
    registeredFarmer: 'नोंदणीकृत शेतकरी',
    myMedicineAdherenceReport: 'माझा औषध पालन अहवाल',
    askVetHelp: 'पशुवैद्यांची मदत घ्या',
    selectAnimal: 'पशू निवडा',
    chooseFromHerd: '-- आपल्या कळपातून निवडा --',
    describeSymptoms: 'लक्षणे लिहा',
    symptomsPlaceholder: 'उदा., खाणे बंद, जास्त ताप...',
    sendingAlert: 'अलर्ट पाठवत आहे...',
    submitRequest: 'विनंती पाठवा',
    treatmentRequestSuccess: 'उपचार विनंती जवळच्या डॉक्टरांना पाठवली!',
    treatmentRequestError: 'विनंती पाठवताना त्रुटी',
    treatmentHistory: 'माझा उपचार इतिहास',
    noTreatmentRecords: 'उपचार रेकॉर्ड सापडले नाहीत.',
    symptomsReported: 'नोंदवलेली लक्षणे',
    vetPrescription: 'पशुवैद्यांचे प्रिस्क्रिप्शन',
    withdrawal: 'विथड्रॉअल',
    days: 'दिवस',
    statusPending: 'प्रलंबित',
    statusAccepted: 'स्वीकारले',
    statusCompleted: 'पूर्ण',
    statusRejected: 'नाकारले',
  },
  gu: {
    registeredFarmer: 'નોંધાયેલ ખેડૂત',
    myMedicineAdherenceReport: 'મારો દવા પાલન રિપોર્ટ',
    askVetHelp: 'વેટ ડૉક્ટરની મદદ લો',
    selectAnimal: 'પશુ પસંદ કરો',
    chooseFromHerd: '-- તમારા પશુઓમાંથી પસંદ કરો --',
    describeSymptoms: 'લક્ષણો લખો',
    symptomsPlaceholder: 'જેમ કે, ખાવું બંધ, વધુ તાવ...',
    sendingAlert: 'એલર્ટ મોકલી રહ્યું છે...',
    submitRequest: 'વિનંતી મોકલો',
    treatmentRequestSuccess: 'ઉપચાર વિનંતી નજીકના ડૉક્ટરોને મોકલાઈ!',
    treatmentRequestError: 'વિનંતી મોકલવામાં ભૂલ',
    treatmentHistory: 'મારો ઉપચાર ઇતિહાસ',
    noTreatmentRecords: 'કોઈ ઉપચાર રેકોર્ડ મળ્યો નથી.',
    symptomsReported: 'જણાવેલા લક્ષણો',
    vetPrescription: 'વેટ ડૉક્ટરની પર્ચી',
    withdrawal: 'વીથડ્રોઅલ',
    days: 'દિવસ',
    statusPending: 'બાકી',
    statusAccepted: 'સ્વીકારેલ',
    statusCompleted: 'પૂર્ણ',
    statusRejected: 'નકારેલ',
  },
  ta: {
    registeredFarmer: 'பதிவு செய்யப்பட்ட விவசாயி',
    myMedicineAdherenceReport: 'என் மருந்து பின்பற்றல் அறிக்கை',
    askVetHelp: 'கால்நடை மருத்துவர் உதவி',
    selectAnimal: 'விலங்கைத் தேர்வு செய்யவும்',
    chooseFromHerd: '-- உங்கள் மந்தையிலிருந்து தேர்வு செய்யவும் --',
    describeSymptoms: 'அறிகுறிகளை எழுதவும்',
    symptomsPlaceholder: 'எ.கா., உணவு நிறுத்தம், அதிக காய்ச்சல்...',
    sendingAlert: 'அலர்ட் அனுப்புகிறது...',
    submitRequest: 'கோரிக்கை அனுப்பு',
    treatmentRequestSuccess: 'சிகிச்சை கோரிக்கை அருகிலுள்ள மருத்துவர்களுக்கு அனுப்பப்பட்டது!',
    treatmentRequestError: 'கோரிக்கை அனுப்புவதில் பிழை',
    treatmentHistory: 'என் சிகிச்சை வரலாறு',
    noTreatmentRecords: 'சிகிச்சை பதிவுகள் இல்லை.',
    symptomsReported: 'தெரிவிக்கப்பட்ட அறிகுறிகள்',
    vetPrescription: 'கால்நடை மருத்துவர் பரிந்துரை',
    withdrawal: 'விலக்கு காலம்',
    days: 'நாட்கள்',
    statusPending: 'நிலுவை',
    statusAccepted: 'ஏற்றுக்கொள்ளப்பட்டது',
    statusCompleted: 'முடிந்தது',
    statusRejected: 'நிராகரிக்கப்பட்டது',
  },
};

Object.entries(farmerText).forEach(([code, values]) => {
  Object.assign(translations[code], values);
});

const reportText = {
  en: {
    mlPrototype: 'Meditrack ML Prototype',
    generatingReport: 'Generating Meditrack AI report...',
    aiRouteRestart: 'AI report route is not active yet. Restart the backend server to load the new /api/ai-report API.',
    unableLoadAiReport: 'Unable to load AI report',
    recommendations: 'Recommendations',
    refresh: 'Refresh',
    reminderQueued: 'Reminder queued',
    addReminder: 'Add reminder',
    copied: 'Copied',
    copyInsight: 'Copy insight',
    adherence: 'Adherence',
    dosesTaken: '{taken}/{total} doses taken',
    healthScore: 'Health score',
    futureMissRisk: 'Future miss risk',
    trend: 'Trend',
    trendChange: '{delta}% change',
    trendAnalysis: 'Trend Analysis',
    adherenceOverTime: 'Adherence over time',
    patternDetection: 'Pattern Detection',
    mostMissedTime: 'Most missed time',
    detectedCluster: 'Detected cluster',
    methodTimeClustering: 'Time-slot clustering by missed-dose frequency',
    medicineWiseAnalysis: 'Medicine-wise Analysis',
    missedOutOf: '{missed} missed out of {total}',
    smartRecommendations: 'Smart Recommendations',
    dataSource: 'Data source',
    demoFallbackData: 'Demo fallback data',
    estimatedBilling: 'Estimated from billing history',
    estimatedTreatment: 'Estimated from treatment history',
    reportStatusHigh: 'High',
    reportStatusMedium: 'Medium',
    reportStatusLow: 'Low',
    reportStatusHealthy: 'Healthy',
    reportStatusModerate: 'Moderate',
    reportStatusCritical: 'Critical',
    reportStatusImproving: 'Improving',
    reportStatusStable: 'Stable',
    reportStatusDeclining: 'Declining',
    timeMorning: 'Morning',
    timeAfternoon: 'Afternoon',
    timeNight: 'Night',
    aiInsight: 'The user most often misses medicines in the {timeSlot}. Adherence is {adherenceClass}, health status is {healthClass}, and future missed-dose risk is {riskLevel}. Trend is {trendDirection}.',
    aiInsightWorstMedicine: ' The medicine that needs the most attention is {medicine}.',
    recNight: 'Move the night-dose reminder earlier and connect it with a fixed routine like shed closing or evening feeding.',
    recMorning: 'Set the morning reminder before farm work starts so the dose is not missed during the busy first hour.',
    recAfternoon: 'Add a midday reminder because missed doses are clustering around the afternoon.',
    recLow: 'Use a two-step reminder: first alert the farmer, then confirm after the medicine is marked taken.',
    recMedium: 'Keep the same treatment plan, but use a daily checklist until adherence stays above 85 percent.',
    recHigh: 'Adherence is strong. Continue the current routine and keep watching for sudden missed-dose spikes.',
    recRiskHigh: 'Flag this animal for follow-up because the predicted chance of missing future doses is high.',
    recDeclining: 'Review recent treatment days because adherence is declining compared with earlier doses.',
    recWorstMedicine: 'Pay extra attention to {medicine}, which has the highest missed-dose count.',
    recVetApproval: 'Do not change dosage without veterinarian approval.',
  },
  hi: {
    mlPrototype: 'Meditrack एमएल प्रोटोटाइप',
    generatingReport: 'Meditrack AI रिपोर्ट बन रही है...',
    aiRouteRestart: 'AI रिपोर्ट रूट अभी सक्रिय नहीं है। नया /api/ai-report API लोड करने के लिए backend server को restart करें।',
    unableLoadAiReport: 'AI रिपोर्ट लोड नहीं हो सकी',
    recommendations: 'सुझाव',
    refresh: 'रिफ्रेश',
    reminderQueued: 'रिमाइंडर लग गया',
    addReminder: 'रिमाइंडर जोड़ें',
    copied: 'कॉपी हो गया',
    copyInsight: 'इनसाइट कॉपी करें',
    adherence: 'दवा पालन',
    dosesTaken: '{taken}/{total} खुराक ली गई',
    healthScore: 'स्वास्थ्य स्कोर',
    futureMissRisk: 'भविष्य में खुराक छूटने का जोखिम',
    trend: 'रुझान',
    trendChange: '{delta}% बदलाव',
    trendAnalysis: 'रुझान विश्लेषण',
    adherenceOverTime: 'समय के साथ दवा पालन',
    patternDetection: 'पैटर्न पहचान',
    mostMissedTime: 'सबसे ज्यादा छूटा समय',
    detectedCluster: 'पहचाना गया समूह',
    methodTimeClustering: 'छूटी हुई खुराक की संख्या के आधार पर समय-समूह विश्लेषण',
    medicineWiseAnalysis: 'दवा के अनुसार विश्लेषण',
    missedOutOf: '{total} में से {missed} छूटी',
    smartRecommendations: 'स्मार्ट सुझाव',
    dataSource: 'डेटा स्रोत',
    demoFallbackData: 'डेमो डेटा',
    estimatedBilling: 'बिलिंग इतिहास से अनुमानित',
    estimatedTreatment: 'उपचार इतिहास से अनुमानित',
    reportStatusHigh: 'उच्च',
    reportStatusMedium: 'मध्यम',
    reportStatusLow: 'कम',
    reportStatusHealthy: 'स्वस्थ',
    reportStatusModerate: 'मध्यम',
    reportStatusCritical: 'गंभीर',
    reportStatusImproving: 'सुधर रहा है',
    reportStatusStable: 'स्थिर',
    reportStatusDeclining: 'घट रहा है',
    timeMorning: 'सुबह',
    timeAfternoon: 'दोपहर',
    timeNight: 'रात',
    aiInsight: 'उपयोगकर्ता सबसे ज्यादा {timeSlot} की दवा छोड़ता है। दवा पालन {adherenceClass} है, स्वास्थ्य स्थिति {healthClass} है, और भविष्य में खुराक छूटने का जोखिम {riskLevel} है। रुझान {trendDirection} है।',
    aiInsightWorstMedicine: ' सबसे ज्यादा ध्यान देने वाली दवा {medicine} है।',
    recNight: 'रात की दवा का रिमाइंडर थोड़ा पहले लगाएं और इसे शाम की फीडिंग या शेड बंद करने जैसी निश्चित दिनचर्या से जोड़ें।',
    recMorning: 'सुबह खेत का काम शुरू होने से पहले रिमाइंडर लगाएं ताकि व्यस्त समय में खुराक न छूटे।',
    recAfternoon: 'दोपहर में रिमाइंडर जोड़ें क्योंकि छूटी हुई खुराकें दोपहर के आसपास अधिक दिख रही हैं।',
    recLow: 'दो-स्तरीय रिमाइंडर उपयोग करें: पहले किसान को अलर्ट दें, फिर दवा ली गई है या नहीं इसकी पुष्टि करें।',
    recMedium: 'उपचार योजना वही रखें, लेकिन दवा पालन 85 प्रतिशत से ऊपर रहने तक दैनिक चेकलिस्ट उपयोग करें।',
    recHigh: 'दवा पालन अच्छा है। वर्तमान दिनचर्या जारी रखें और अचानक खुराक छूटने पर नजर रखें।',
    recRiskHigh: 'इस पशु को follow-up के लिए चिह्नित करें क्योंकि भविष्य में खुराक छूटने की संभावना अधिक है।',
    recDeclining: 'हाल के उपचार दिनों की समीक्षा करें क्योंकि पहले की तुलना में दवा पालन घट रहा है।',
    recWorstMedicine: '{medicine} पर विशेष ध्यान दें, क्योंकि इसी दवा की खुराक सबसे ज्यादा छूटी है।',
    recVetApproval: 'पशु चिकित्सक की अनुमति के बिना खुराक न बदलें।',
  },
  mr: {
    mlPrototype: 'Meditrack एमएल प्रोटोटाइप',
    generatingReport: 'Meditrack AI अहवाल तयार होत आहे...',
    aiRouteRestart: 'AI अहवाल मार्ग अजून सक्रिय नाही. नवीन /api/ai-report API लोड करण्यासाठी backend server पुन्हा सुरू करा.',
    unableLoadAiReport: 'AI अहवाल लोड होऊ शकला नाही',
    recommendations: 'शिफारसी',
    refresh: 'रीफ्रेश',
    reminderQueued: 'रिमाइंडर लावला',
    addReminder: 'रिमाइंडर जोडा',
    copied: 'कॉपी झाले',
    copyInsight: 'इनसाइट कॉपी करा',
    adherence: 'औषध पालन',
    dosesTaken: '{taken}/{total} डोस घेतले',
    healthScore: 'आरोग्य स्कोर',
    futureMissRisk: 'भविष्यात डोस चुकण्याचा धोका',
    trend: 'कल',
    trendChange: '{delta}% बदल',
    trendAnalysis: 'कल विश्लेषण',
    adherenceOverTime: 'वेळेनुसार औषध पालन',
    patternDetection: 'पॅटर्न ओळख',
    mostMissedTime: 'सर्वाधिक चुकलेला वेळ',
    detectedCluster: 'ओळखलेला समूह',
    methodTimeClustering: 'चुकलेल्या डोसच्या संख्येनुसार वेळ-समूह विश्लेषण',
    medicineWiseAnalysis: 'औषधानुसार विश्लेषण',
    missedOutOf: '{total} पैकी {missed} चुकले',
    smartRecommendations: 'स्मार्ट शिफारसी',
    dataSource: 'डेटा स्रोत',
    demoFallbackData: 'डेमो डेटा',
    estimatedBilling: 'बिलिंग इतिहासावरून अंदाजित',
    estimatedTreatment: 'उपचार इतिहासावरून अंदाजित',
    reportStatusHigh: 'उच्च',
    reportStatusMedium: 'मध्यम',
    reportStatusLow: 'कमी',
    reportStatusHealthy: 'निरोगी',
    reportStatusModerate: 'मध्यम',
    reportStatusCritical: 'गंभीर',
    reportStatusImproving: 'सुधारत आहे',
    reportStatusStable: 'स्थिर',
    reportStatusDeclining: 'घसरत आहे',
    timeMorning: 'सकाळ',
    timeAfternoon: 'दुपार',
    timeNight: 'रात्र',
    aiInsight: 'वापरकर्ता सर्वाधिक {timeSlot} चा डोस चुकवतो. औषध पालन {adherenceClass} आहे, आरोग्य स्थिती {healthClass} आहे, आणि भविष्यात डोस चुकण्याचा धोका {riskLevel} आहे. कल {trendDirection} आहे.',
    aiInsightWorstMedicine: ' सर्वाधिक लक्ष देण्याची गरज असलेले औषध {medicine} आहे.',
    recNight: 'रात्रीच्या डोसचा रिमाइंडर थोडा आधी ठेवा आणि तो संध्याकाळचे खाद्य देणे किंवा शेड बंद करणे अशा ठराविक सवयीशी जोडा.',
    recMorning: 'सकाळचे शेतकाम सुरू होण्यापूर्वी रिमाइंडर ठेवा, म्हणजे व्यस्त पहिल्या तासात डोस चुकणार नाही.',
    recAfternoon: 'दुपारच्या सुमारास डोस चुकत असल्याने मध्यान्ह रिमाइंडर जोडा.',
    recLow: 'दोन-स्तरीय रिमाइंडर वापरा: आधी शेतकऱ्याला अलर्ट, नंतर औषध घेतल्याची पुष्टी.',
    recMedium: 'उपचार योजना तशीच ठेवा, पण औषध पालन 85 टक्क्यांपेक्षा जास्त होईपर्यंत रोजची चेकलिस्ट वापरा.',
    recHigh: 'औषध पालन चांगले आहे. सध्याची दिनचर्या सुरू ठेवा आणि अचानक डोस चुकण्यावर लक्ष ठेवा.',
    recRiskHigh: 'भविष्यात डोस चुकण्याची शक्यता जास्त असल्याने या पशूचा फॉलो-अप करा.',
    recDeclining: 'औषध पालन आधीपेक्षा कमी होत असल्याने अलीकडच्या उपचार दिवसांची तपासणी करा.',
    recWorstMedicine: '{medicine} कडे विशेष लक्ष द्या, कारण त्याचे डोस सर्वाधिक चुकले आहेत.',
    recVetApproval: 'पशुवैद्यांच्या परवानगीशिवाय डोस बदलू नका.',
  },
  gu: {
    mlPrototype: 'Meditrack એમએલ પ્રોટોટાઇપ',
    generatingReport: 'Meditrack AI રિપોર્ટ તૈયાર થઈ રહ્યો છે...',
    aiRouteRestart: 'AI રિપોર્ટ રૂટ હજી સક્રિય નથી. નવી /api/ai-report API લોડ કરવા માટે backend server ફરી શરૂ કરો.',
    unableLoadAiReport: 'AI રિપોર્ટ લોડ થઈ શક્યો નથી',
    recommendations: 'ભલામણો',
    refresh: 'રિફ્રેશ',
    reminderQueued: 'રિમાઇન્ડર લગાવ્યું',
    addReminder: 'રિમાઇન્ડર ઉમેરો',
    copied: 'કોપી થયું',
    copyInsight: 'ઇનસાઇટ કોપી કરો',
    adherence: 'દવા પાલન',
    dosesTaken: '{taken}/{total} ડોઝ લીધા',
    healthScore: 'આરોગ્ય સ્કોર',
    futureMissRisk: 'ભવિષ્યમાં ડોઝ ચૂકી જવાનો જોખમ',
    trend: 'વલણ',
    trendChange: '{delta}% ફેરફાર',
    trendAnalysis: 'વલણ વિશ્લેષણ',
    adherenceOverTime: 'સમય સાથે દવા પાલન',
    patternDetection: 'પેટર્ન ઓળખ',
    mostMissedTime: 'સૌથી વધુ ચૂકી ગયેલો સમય',
    detectedCluster: 'ઓળખાયેલો સમૂહ',
    methodTimeClustering: 'ચૂકેલા ડોઝની સંખ્યા પ્રમાણે સમય-સમૂહ વિશ્લેષણ',
    medicineWiseAnalysis: 'દવા મુજબ વિશ્લેષણ',
    missedOutOf: '{total} માંથી {missed} ચૂકી ગયા',
    smartRecommendations: 'સ્માર્ટ ભલામણો',
    dataSource: 'ડેટા સ્ત્રોત',
    demoFallbackData: 'ડેમો ડેટા',
    estimatedBilling: 'બિલિંગ ઇતિહાસ પરથી અંદાજિત',
    estimatedTreatment: 'ઉપચાર ઇતિહાસ પરથી અંદાજિત',
    reportStatusHigh: 'ઉચ્ચ',
    reportStatusMedium: 'મધ્યમ',
    reportStatusLow: 'નીચું',
    reportStatusHealthy: 'સ્વસ્થ',
    reportStatusModerate: 'મધ્યમ',
    reportStatusCritical: 'ગંભીર',
    reportStatusImproving: 'સુધરી રહ્યું છે',
    reportStatusStable: 'સ્થિર',
    reportStatusDeclining: 'ઘટી રહ્યું છે',
    timeMorning: 'સવાર',
    timeAfternoon: 'બપોર',
    timeNight: 'રાત',
    aiInsight: 'વપરાશકર્તા સૌથી વધુ {timeSlot} નો ડોઝ ચૂકે છે. દવા પાલન {adherenceClass} છે, આરોગ્ય સ્થિતિ {healthClass} છે, અને ભવિષ્યમાં ડોઝ ચૂકી જવાનો જોખમ {riskLevel} છે. વલણ {trendDirection} છે.',
    aiInsightWorstMedicine: ' સૌથી વધુ ધ્યાન આપવાની દવા {medicine} છે.',
    recNight: 'રાતના ડોઝનું રિમાઇન્ડર થોડું વહેલું મૂકો અને તેને સાંજનું ખોરાક આપવું અથવા શેડ બંધ કરવું જેવી નક્કી સવય સાથે જોડો.',
    recMorning: 'સવારનું ખેતરનું કામ શરૂ થાય તે પહેલાં રિમાઇન્ડર મૂકો, જેથી વ્યસ્ત પહેલા કલાકમાં ડોઝ ન ચૂકે.',
    recAfternoon: 'બપોરે ડોઝ ચૂકી જવાની પૅટર્ન હોવાથી મધ્યાહ્ન રિમાઇન્ડર ઉમેરો.',
    recLow: 'બે-સ્તરનું રિમાઇન્ડર વાપરો: પહેલા ખેડૂતને એલર્ટ, પછી દવા લેવામાં આવી કે નહીં તેની પુષ્ટિ.',
    recMedium: 'ઉપચાર યોજના એ જ રાખો, પણ પાલન 85 ટકા ઉપર રહે ત્યાં સુધી દૈનિક ચેકલિસ્ટ વાપરો.',
    recHigh: 'દવા પાલન મજબૂત છે. હાલની સવય ચાલુ રાખો અને અચાનક ડોઝ ચૂકે તો નજર રાખો.',
    recRiskHigh: 'ભવિષ્યમાં ડોઝ ચૂકી જવાની શક્યતા વધારે હોવાથી આ પશુ માટે ફોલો-અપ રાખો.',
    recDeclining: 'દવા પાલન ઘટી રહ્યું હોવાથી તાજેતરના ઉપચાર દિવસો તપાસો.',
    recWorstMedicine: '{medicine} પર વધારે ધ્યાન આપો, કારણ કે તેના ડોઝ સૌથી વધુ ચૂકી ગયા છે.',
    recVetApproval: 'વેટ ડૉક્ટરની મંજૂરી વગર ડોઝ ન બદલશો.',
  },
  ta: {
    mlPrototype: 'Meditrack எம்எல் மாதிரி',
    generatingReport: 'Meditrack AI அறிக்கை உருவாகிறது...',
    aiRouteRestart: 'AI அறிக்கை பாதை இன்னும் செயல்படவில்லை. புதிய /api/ai-report API ஏற்ற backend server-ஐ மீண்டும் தொடங்கவும்.',
    unableLoadAiReport: 'AI அறிக்கையை ஏற்ற முடியவில்லை',
    recommendations: 'பரிந்துரைகள்',
    refresh: 'புதுப்பிக்கவும்',
    reminderQueued: 'நினைவூட்டல் சேர்க்கப்பட்டது',
    addReminder: 'நினைவூட்டல் சேர்',
    copied: 'நகலெடுக்கப்பட்டது',
    copyInsight: 'விளக்கத்தை நகலெடு',
    adherence: 'மருந்து பின்பற்றல்',
    dosesTaken: '{taken}/{total} டோஸ் எடுத்தது',
    healthScore: 'ஆரோக்கிய மதிப்பெண்',
    futureMissRisk: 'எதிர்கால டோஸ் தவறும் அபாயம்',
    trend: 'போக்கு',
    trendChange: '{delta}% மாற்றம்',
    trendAnalysis: 'போக்கு பகுப்பாய்வு',
    adherenceOverTime: 'காலத்தின்படி மருந்து பின்பற்றல்',
    patternDetection: 'முறை கண்டறிதல்',
    mostMissedTime: 'அதிகம் தவறிய நேரம்',
    detectedCluster: 'கண்டறியப்பட்ட குழு',
    methodTimeClustering: 'தவறிய டோஸ் எண்ணிக்கையின் அடிப்படையில் நேரக் குழு பகுப்பாய்வு',
    medicineWiseAnalysis: 'மருந்து வாரியான பகுப்பாய்வு',
    missedOutOf: '{total} இல் {missed} தவறியது',
    smartRecommendations: 'ஸ்மார்ட் பரிந்துரைகள்',
    dataSource: 'தரவு மூலம்',
    demoFallbackData: 'டெமோ தரவு',
    estimatedBilling: 'பில்லிங் வரலாற்றிலிருந்து கணிக்கப்பட்டது',
    estimatedTreatment: 'சிகிச்சை வரலாற்றிலிருந்து கணிக்கப்பட்டது',
    reportStatusHigh: 'உயர்',
    reportStatusMedium: 'நடுத்தரம்',
    reportStatusLow: 'குறைவு',
    reportStatusHealthy: 'ஆரோக்கியம்',
    reportStatusModerate: 'மிதமான',
    reportStatusCritical: 'கடுமை',
    reportStatusImproving: 'மேம்படுகிறது',
    reportStatusStable: 'நிலையானது',
    reportStatusDeclining: 'குறைந்து வருகிறது',
    timeMorning: 'காலை',
    timeAfternoon: 'மதியம்',
    timeNight: 'இரவு',
    aiInsight: 'பயனர் பெரும்பாலும் {timeSlot} மருந்தை தவற விடுகிறார். மருந்து பின்பற்றல் {adherenceClass}, ஆரோக்கிய நிலை {healthClass}, மற்றும் எதிர்கால டோஸ் தவறும் அபாயம் {riskLevel}. போக்கு {trendDirection}.',
    aiInsightWorstMedicine: ' அதிக கவனம் தேவைப்படும் மருந்து {medicine}.',
    recNight: 'இரவு டோஸ் நினைவூட்டலை கொஞ்சம் முன்பாக அமைத்து, மாலை உணவளிப்பு அல்லது ஷெட்டை மூடுதல் போன்ற நிரந்தர பழக்கத்துடன் இணைக்கவும்.',
    recMorning: 'காலை பண்ணை வேலை தொடங்குவதற்கு முன் நினைவூட்டல் அமைக்கவும், இதனால் முதல் பிஸியான நேரத்தில் டோஸ் தவறாது.',
    recAfternoon: 'மதியம் டோஸ் தவறுவது அதிகமாக இருப்பதால் மதிய நினைவூட்டலைச் சேர்க்கவும்.',
    recLow: 'இரண்டு-படி நினைவூட்டலைப் பயன்படுத்தவும்: முதலில் விவசாயிக்கு எச்சரிக்கை, பிறகு மருந்து எடுத்ததை உறுதி செய்யவும்.',
    recMedium: 'சிகிச்சை திட்டத்தை தொடரவும், ஆனால் பின்பற்றல் 85 சதவீதத்துக்கு மேல் நிலையாகும் வரை தினசரி சரிபார்ப்பு பட்டியலைப் பயன்படுத்தவும்.',
    recHigh: 'மருந்து பின்பற்றல் வலுவாக உள்ளது. தற்போதைய பழக்கத்தை தொடரவும், திடீர் தவறுகளை கவனிக்கவும்.',
    recRiskHigh: 'எதிர்காலத்தில் டோஸ் தவறும் வாய்ப்பு அதிகமாக இருப்பதால் இந்த விலங்கிற்கு பின்தொடர்பு தேவை.',
    recDeclining: 'பின்பற்றல் குறைந்து வருவதால் சமீபத்திய சிகிச்சை நாட்களைப் பார்க்கவும்.',
    recWorstMedicine: '{medicine} மீது கூடுதல் கவனம் செலுத்தவும், ஏனெனில் அதில் தவறிய டோஸ் அதிகம்.',
    recVetApproval: 'கால்நடை மருத்துவர் அனுமதி இல்லாமல் டோஸ் மாற்ற வேண்டாம்.',
  },
};

Object.entries(reportText).forEach(([code, values]) => {
  Object.assign(translations[code], values);
});

const extraRegionalLanguages = {
  bn: { languageName: 'বাংলা', farmerCare: 'Meditrack কৃষক সেবা', ...farmerText.hi },
  te: { languageName: 'తెలుగు', farmerCare: 'Meditrack రైతు సేవ', ...farmerText.hi, registeredFarmer: 'నమోదైన రైతు', askVetHelp: 'వెటర్నరీ సహాయం అడగండి', selectAnimal: 'జంతువును ఎంచుకోండి', submitRequest: 'అభ్యర్థన పంపండి', treatmentHistory: 'నా చికిత్స చరిత్ర' },
  kn: { languageName: 'ಕನ್ನಡ', farmerCare: 'Meditrack ರೈತ ಸೇವೆ', ...farmerText.hi, registeredFarmer: 'ನೋಂದಾಯಿತ ರೈತ', askVetHelp: 'ಪಶುವೈದ್ಯರ ಸಹಾಯ ಕೇಳಿ', selectAnimal: 'ಪ್ರಾಣಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ', submitRequest: 'ವಿನಂತಿ ಕಳುಹಿಸಿ', treatmentHistory: 'ನನ್ನ ಚಿಕಿತ್ಸಾ ಇತಿಹಾಸ' },
  ml: { languageName: 'മലയാളം', farmerCare: 'Meditrack കർഷക സേവനം', ...farmerText.hi, registeredFarmer: 'രജിസ്റ്റർ ചെയ്ത കർഷകൻ', askVetHelp: 'വെറ്റ് സഹായം ചോദിക്കുക', selectAnimal: 'മൃഗം തിരഞ്ഞെടുക്കുക', submitRequest: 'അഭ്യർത്ഥന അയയ്ക്കുക', treatmentHistory: 'എന്റെ ചികിത്സ ചരിത്രം' },
  pa: { languageName: 'ਪੰਜਾਬੀ', farmerCare: 'Meditrack ਕਿਸਾਨ ਸੇਵਾ', ...farmerText.hi, registeredFarmer: 'ਰਜਿਸਟਰਡ ਕਿਸਾਨ', askVetHelp: 'ਵੈਟ ਡਾਕਟਰ ਦੀ ਮਦਦ ਲਵੋ', selectAnimal: 'ਪਸ਼ੂ ਚੁਣੋ', submitRequest: 'ਬੇਨਤੀ ਭੇਜੋ', treatmentHistory: 'ਮੇਰਾ ਇਲਾਜ ਇਤਿਹਾਸ' },
  ur: { languageName: 'اردو', farmerCare: 'Meditrack کسان کی دیکھ بھال', ...farmerText.hi, registeredFarmer: 'رجسٹرڈ کسان', askVetHelp: 'ویٹ ڈاکٹر سے مدد لیں', selectAnimal: 'جانور منتخب کریں', submitRequest: 'درخواست بھیجیں', treatmentHistory: 'میری علاج کی تاریخ' },
  od: { languageName: 'ଓଡ଼ିଆ', farmerCare: 'Meditrack କୃଷକ ସେବା', ...farmerText.hi, registeredFarmer: 'ନୋନ୍ଦିତ କୃଷକ', askVetHelp: 'ପଶୁ ଡାକ୍ତର ସହାୟତା ନିଅନ୍ତୁ', selectAnimal: 'ପଶୁ ବାଛନ୍ତୁ', submitRequest: 'ଅନୁରୋଧ ପଠାନ୍ତୁ', treatmentHistory: 'ମୋର ଚିକିତ୍ସା ଇତିହାସ' },
  as: { languageName: 'অসমীয়া', farmerCare: 'Meditrack কৃষক সেৱা', ...farmerText.hi, registeredFarmer: 'পঞ্জীয়ন কৰা কৃষক', askVetHelp: 'পশু চিকিৎসকৰ সহায় লওক', selectAnimal: 'পশু বাছনি কৰক', submitRequest: 'অনুৰোধ পঠাওক', treatmentHistory: 'মোৰ চিকিৎসা ইতিহাস' },
};

const extraRegionalUiText = {
  bn: {
    theme: 'থিম',
    light: 'লাইট',
    dark: 'ডার্ক',
    language: 'ভাষা',
    signOut: 'সাইন আউট',
    loginTitle: 'ফিরে আসায় স্বাগতম',
    loginSubtitle: 'আপনার Meditrack ড্যাশবোর্ডে যেতে তথ্য লিখুন।',
    phoneNumber: 'ফোন নম্বর',
    password: 'পাসওয়ার্ড',
    enterPassword: 'আপনার পাসওয়ার্ড লিখুন',
    signIn: 'নিরাপদে সাইন ইন',
    signingIn: 'সাইন ইন হচ্ছে...',
    noAccount: 'অ্যাকাউন্ট নেই?',
    signupHere: 'এখানে সাইন আপ করুন',
    demoShortcuts: 'ডেমো লগইন শর্টকাট',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    joinNetwork: 'নেটওয়ার্কে যোগ দিন',
    registerCopy: 'পশু স্বাস্থ্য, প্রেসক্রিপশন, AI ওষুধ পালন ইনসাইট এবং AMU ডেটা পরিচালনার জন্য অ্যাকাউন্ট তৈরি করুন।',
    fullName: 'পুরো নাম',
    city: 'শহর/জেলা',
    role: 'ভূমিকা নির্বাচন করুন',
    createMeditrackAccount: 'Meditrack অ্যাকাউন্ট তৈরি করুন',
    creatingAccount: 'অ্যাকাউন্ট তৈরি হচ্ছে...',
    alreadyAccount: 'আগে থেকেই অ্যাকাউন্ট আছে?',
    loginHere: 'এখানে লগ ইন করুন',
    registeredFarmer: 'নিবন্ধিত কৃষক',
    myMedicineAdherenceReport: 'আমার ওষুধ পালন রিপোর্ট',
    askVetHelp: 'পশু ডাক্তারের সাহায্য নিন',
    selectAnimal: 'পশু নির্বাচন করুন',
    chooseFromHerd: '-- আপনার পশুর দল থেকে নির্বাচন করুন --',
    describeSymptoms: 'লক্ষণ লিখুন',
    symptomsPlaceholder: 'যেমন, খাওয়া বন্ধ, বেশি জ্বর...',
    sendingAlert: 'সতর্কবার্তা পাঠানো হচ্ছে...',
    submitRequest: 'অনুরোধ পাঠান',
    treatmentRequestSuccess: 'চিকিৎসার অনুরোধ কাছের ডাক্তারদের কাছে পাঠানো হয়েছে!',
    treatmentRequestError: 'অনুরোধ পাঠাতে সমস্যা হয়েছে',
    treatmentHistory: 'আমার চিকিৎসার ইতিহাস',
    noTreatmentRecords: 'কোনো চিকিৎসা রেকর্ড পাওয়া যায়নি।',
    symptomsReported: 'জানানো লক্ষণ',
    vetPrescription: 'পশু ডাক্তারের প্রেসক্রিপশন',
    withdrawal: 'প্রত্যাহার সময়',
    days: 'দিন',
    statusPending: 'অপেক্ষমান',
    statusAccepted: 'গৃহীত',
    statusCompleted: 'সম্পন্ন',
    statusRejected: 'প্রত্যাখ্যাত',
    mlPrototype: 'Meditrack এমএল প্রোটোটাইপ',
    refresh: 'রিফ্রেশ',
    addReminder: 'রিমাইন্ডার যোগ করুন',
    reminderQueued: 'রিমাইন্ডার যুক্ত হয়েছে',
    copied: 'কপি হয়েছে',
    copyInsight: 'ইনসাইট কপি করুন',
    recommendations: 'পরামর্শ',
    adherence: 'ওষুধ পালন',
    dosesTaken: '{taken}/{total} ডোজ নেওয়া হয়েছে',
    healthScore: 'স্বাস্থ্য স্কোর',
    futureMissRisk: 'ভবিষ্যতে ডোজ মিসের ঝুঁকি',
    trend: 'প্রবণতা',
    trendChange: '{delta}% পরিবর্তন',
    trendAnalysis: 'প্রবণতা বিশ্লেষণ',
    adherenceOverTime: 'সময়ের সাথে ওষুধ পালন',
    patternDetection: 'প্যাটার্ন শনাক্তকরণ',
    mostMissedTime: 'সবচেয়ে বেশি মিস হওয়া সময়',
    detectedCluster: 'শনাক্ত করা গ্রুপ',
    methodTimeClustering: 'মিস হওয়া ডোজের সংখ্যার ভিত্তিতে সময়-গ্রুপ বিশ্লেষণ',
    medicineWiseAnalysis: 'ওষুধভিত্তিক বিশ্লেষণ',
    missedOutOf: '{total} এর মধ্যে {missed} মিস',
    smartRecommendations: 'স্মার্ট পরামর্শ',
    dataSource: 'ডেটা উৎস',
    demoFallbackData: 'ডেমো ডেটা',
    estimatedBilling: 'বিলিং ইতিহাস থেকে অনুমান',
    estimatedTreatment: 'চিকিৎসা ইতিহাস থেকে অনুমান',
    reportStatusHigh: 'উচ্চ',
    reportStatusMedium: 'মাঝারি',
    reportStatusLow: 'কম',
    reportStatusHealthy: 'সুস্থ',
    reportStatusModerate: 'মাঝারি',
    reportStatusCritical: 'গুরুতর',
    reportStatusImproving: 'উন্নতি হচ্ছে',
    reportStatusStable: 'স্থিতিশীল',
    reportStatusDeclining: 'কমছে',
    timeMorning: 'সকাল',
    timeAfternoon: 'দুপুর',
    timeNight: 'রাত',
    aiInsight: 'ব্যবহারকারী সবচেয়ে বেশি {timeSlot} এর ওষুধ মিস করেন। ওষুধ পালন {adherenceClass}, স্বাস্থ্য অবস্থা {healthClass}, এবং ভবিষ্যতে ডোজ মিসের ঝুঁকি {riskLevel}। প্রবণতা {trendDirection}।',
    aiInsightWorstMedicine: ' সবচেয়ে বেশি নজর দরকার {medicine} ওষুধে।',
    recNight: 'রাতের ডোজের রিমাইন্ডার একটু আগে দিন এবং সন্ধ্যার খাওয়ানো বা শেড বন্ধ করার অভ্যাসের সঙ্গে যুক্ত করুন।',
    recMorning: 'সকালের কাজ শুরু হওয়ার আগে রিমাইন্ডার দিন, যাতে ব্যস্ত সময়ে ডোজ মিস না হয়।',
    recAfternoon: 'দুপুরে ডোজ মিস বেশি হচ্ছে, তাই দুপুরের রিমাইন্ডার যোগ করুন।',
    recLow: 'দুই ধাপের রিমাইন্ডার ব্যবহার করুন: আগে কৃষককে সতর্ক করুন, পরে ওষুধ নেওয়া নিশ্চিত করুন।',
    recMedium: 'চিকিৎসা পরিকল্পনা চালু রাখুন, তবে পালন 85 শতাংশের ওপরে না থাকা পর্যন্ত দৈনিক চেকলিস্ট ব্যবহার করুন।',
    recHigh: 'ওষুধ পালন ভালো। বর্তমান রুটিন চালিয়ে যান এবং হঠাৎ ডোজ মিস হচ্ছে কি না নজর রাখুন।',
    recRiskHigh: 'ভবিষ্যতে ডোজ মিসের সম্ভাবনা বেশি, তাই এই পশুর ফলো-আপ রাখুন।',
    recDeclining: 'পালন কমছে, তাই সাম্প্রতিক চিকিৎসার দিনগুলো পর্যালোচনা করুন।',
    recWorstMedicine: '{medicine} এর দিকে বেশি নজর দিন, কারণ এই ওষুধের ডোজ সবচেয়ে বেশি মিস হয়েছে।',
    recVetApproval: 'পশু ডাক্তারের অনুমতি ছাড়া ডোজ পরিবর্তন করবেন না।',
  },
  te: {
    theme: 'థీమ్',
    light: 'లైట్',
    dark: 'డార్క్',
    language: 'భాష',
    signOut: 'సైన్ అవుట్',
    loginTitle: 'తిరిగి స్వాగతం',
    loginSubtitle: 'మీ Meditrack డ్యాష్‌బోర్డ్‌లోకి వెళ్లడానికి వివరాలు నమోదు చేయండి.',
    phoneNumber: 'ఫోన్ నంబర్',
    password: 'పాస్‌వర్డ్',
    enterPassword: 'మీ పాస్‌వర్డ్ నమోదు చేయండి',
    signIn: 'సురక్షితంగా సైన్ ఇన్',
    signingIn: 'సైన్ ఇన్ అవుతోంది...',
    noAccount: 'ఖాతా లేదా?',
    signupHere: 'ఇక్కడ సైన్ అప్ చేయండి',
    demoShortcuts: 'డెమో లాగిన్ షార్ట్‌కట్‌లు',
    createAccount: 'ఖాతా సృష్టించండి',
    joinNetwork: 'నెట్‌వర్క్‌లో చేరండి',
    registerCopy: 'పశు ఆరోగ్యం, ప్రిస్క్రిప్షన్లు, AI ఔషధ పాటింపు సమాచారం మరియు AMU డేటాను నిర్వహించడానికి ఖాతా సృష్టించండి.',
    fullName: 'పూర్తి పేరు',
    city: 'నగరం/జిల్లా',
    role: 'పాత్రను ఎంచుకోండి',
    createMeditrackAccount: 'Meditrack ఖాతా సృష్టించండి',
    creatingAccount: 'ఖాతా సృష్టిస్తోంది...',
    alreadyAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    loginHere: 'ఇక్కడ లాగిన్ చేయండి',
    myMedicineAdherenceReport: 'నా ఔషధ పాటింపు నివేదిక',
    chooseFromHerd: '-- మీ మంద నుండి ఎంచుకోండి --',
    describeSymptoms: 'లక్షణాలు వ్రాయండి',
    symptomsPlaceholder: 'ఉదా., తినడం ఆపింది, ఎక్కువ జ్వరం...',
    sendingAlert: 'అలర్ట్ పంపుతోంది...',
    treatmentRequestSuccess: 'చికిత్స అభ్యర్థన సమీప వైద్యులకు పంపబడింది!',
    treatmentRequestError: 'అభ్యర్థన పంపడంలో లోపం',
    noTreatmentRecords: 'చికిత్స రికార్డులు కనబడలేదు.',
    symptomsReported: 'నివేదించిన లక్షణాలు',
    vetPrescription: 'వెట్ వైద్యుని ప్రిస్క్రిప్షన్',
    withdrawal: 'విడితి కాలం',
    days: 'రోజులు',
    mlPrototype: 'Meditrack ఎంఎల్ నమూనా',
    refresh: 'రిఫ్రెష్',
    addReminder: 'రిమైండర్ జోడించండి',
    reminderQueued: 'రిమైండర్ జోడించబడింది',
    copied: 'కాపీ అయింది',
    copyInsight: 'ఇన్‌సైట్ కాపీ చేయండి',
    adherence: 'ఔషధ పాటింపు',
    dosesTaken: '{taken}/{total} డోసులు తీసుకున్నారు',
    healthScore: 'ఆరోగ్య స్కోరు',
    futureMissRisk: 'భవిష్యత్తులో డోస్ మిస్ అయ్యే ప్రమాదం',
    trend: 'ధోరణి',
    trendChange: '{delta}% మార్పు',
    trendAnalysis: 'ధోరణి విశ్లేషణ',
    adherenceOverTime: 'కాలక్రమంలో ఔషధ పాటింపు',
    patternDetection: 'నమూనా గుర్తింపు',
    mostMissedTime: 'ఎక్కువగా మిస్ అయిన సమయం',
    detectedCluster: 'గుర్తించిన సమూహం',
    methodTimeClustering: 'మిస్ అయిన డోసుల సంఖ్య ఆధారంగా సమయ-సమూహ విశ్లేషణ',
    medicineWiseAnalysis: 'ఔషధాల వారీ విశ్లేషణ',
    missedOutOf: '{total} లో {missed} మిస్ అయ్యాయి',
    smartRecommendations: 'స్మార్ట్ సూచనలు',
    dataSource: 'డేటా మూలం',
    demoFallbackData: 'డెమో డేటా',
    estimatedBilling: 'బిల్లింగ్ చరిత్ర ఆధారంగా అంచనా',
    estimatedTreatment: 'చికిత్స చరిత్ర ఆధారంగా అంచనా',
    reportStatusHigh: 'అధిక',
    reportStatusMedium: 'మధ్యస్థ',
    reportStatusLow: 'తక్కువ',
    reportStatusHealthy: 'ఆరోగ్యంగా',
    reportStatusModerate: 'మధ్యస్థ',
    reportStatusCritical: 'తీవ్రం',
    reportStatusImproving: 'మెరుగవుతోంది',
    reportStatusStable: 'స్థిరంగా',
    reportStatusDeclining: 'తగ్గుతోంది',
    timeMorning: 'ఉదయం',
    timeAfternoon: 'మధ్యాహ్నం',
    timeNight: 'రాత్రి',
    aiInsight: 'వినియోగదారు ఎక్కువగా {timeSlot} ఔషధాన్ని మిస్ చేస్తున్నారు. ఔషధ పాటింపు {adherenceClass}, ఆరోగ్య స్థితి {healthClass}, భవిష్యత్తులో డోస్ మిస్ అయ్యే ప్రమాదం {riskLevel}. ధోరణి {trendDirection}.',
    aiInsightWorstMedicine: ' ఎక్కువ శ్రద్ధ అవసరమైన ఔషధం {medicine}.',
    recNight: 'రాత్రి డోస్ రిమైండర్‌ను కొంచెం ముందుగా పెట్టి, సాయంత్రం ఆహారం పెట్టడం లేదా షెడ్ మూయడం వంటి అలవాటుతో కలపండి.',
    recMorning: 'ఉదయం పంట పని మొదలయ్యే ముందు రిమైండర్ పెట్టండి, అప్పుడు బిజీ సమయంలో డోస్ మిస్ కాదు.',
    recAfternoon: 'మధ్యాహ్నం డోసులు ఎక్కువగా మిస్ అవుతున్నందున మధ్యాహ్న రిమైండర్ జోడించండి.',
    recLow: 'రెండు దశల రిమైండర్ వాడండి: ముందుగా రైతుకు అలర్ట్, తర్వాత ఔషధం తీసుకున్నదా అని నిర్ధారణ.',
    recMedium: 'చికిత్స ప్రణాళికను కొనసాగించండి, కానీ పాటింపు 85 శాతం దాటే వరకు రోజువారీ చెక్‌లిస్ట్ వాడండి.',
    recHigh: 'ఔషధ పాటింపు బలంగా ఉంది. ప్రస్తుత రొటీన్ కొనసాగించి, ఒక్కసారిగా డోస్ మిస్ అయితే గమనించండి.',
    recRiskHigh: 'భవిష్యత్తులో డోస్ మిస్ అయ్యే అవకాశం ఎక్కువగా ఉంది కాబట్టి ఈ జంతువుకు ఫాలో-అప్ పెట్టండి.',
    recDeclining: 'పాటింపు తగ్గుతోంది, కాబట్టి ఇటీవలి చికిత్స రోజులను పరిశీలించండి.',
    recWorstMedicine: '{medicine} పై ఎక్కువ శ్రద్ధ పెట్టండి, ఎందుకంటే ఈ ఔషధం డోసులు ఎక్కువగా మిస్ అయ్యాయి.',
    recVetApproval: 'వెట్ వైద్యుని అనుమతి లేకుండా డోస్ మార్చవద్దు.',
  },
  kn: {
    theme: 'ಥೀಮ್',
    light: 'ಲೈಟ್',
    dark: 'ಡಾರ್ಕ್',
    language: 'ಭಾಷೆ',
    signOut: 'ಸೈನ್ ಔಟ್',
    loginTitle: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    loginSubtitle: 'ನಿಮ್ಮ Meditrack ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಲು ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.',
    phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    enterPassword: 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    signIn: 'ಸುರಕ್ಷಿತವಾಗಿ ಸೈನ್ ಇನ್',
    signingIn: 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    signupHere: 'ಇಲ್ಲಿ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    demoShortcuts: 'ಡೆಮೋ ಲಾಗಿನ್ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    joinNetwork: 'ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ',
    registerCopy: 'ಪಶು ಆರೋಗ್ಯ, ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್, AI ಔಷಧ ಪಾಲನೆ ಮಾಹಿತಿ ಮತ್ತು AMU ಡೇಟಾ ನಿರ್ವಹಿಸಲು ಖಾತೆ ರಚಿಸಿ.',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    city: 'ನಗರ/ಜಿಲ್ಲೆ',
    role: 'ಪಾತ್ರ ಆಯ್ಕೆಮಾಡಿ',
    createMeditrackAccount: 'Meditrack ಖಾತೆ ರಚಿಸಿ',
    creatingAccount: 'ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    alreadyAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    loginHere: 'ಇಲ್ಲಿ ಲಾಗಿನ್ ಮಾಡಿ',
    myMedicineAdherenceReport: 'ನನ್ನ ಔಷಧ ಪಾಲನೆ ವರದಿ',
    chooseFromHerd: '-- ನಿಮ್ಮ ಹಿಂಡಿನಿಂದ ಆಯ್ಕೆಮಾಡಿ --',
    describeSymptoms: 'ಲಕ್ಷಣಗಳನ್ನು ಬರೆಯಿರಿ',
    symptomsPlaceholder: 'ಉದಾ., ತಿನ್ನುವುದು ನಿಂತಿದೆ, ಹೆಚ್ಚು ಜ್ವರ...',
    sendingAlert: 'ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
    treatmentRequestSuccess: 'ಚಿಕಿತ್ಸಾ ವಿನಂತಿ ಹತ್ತಿರದ ವೈದ್ಯರಿಗೆ ಕಳುಹಿಸಲಾಗಿದೆ!',
    treatmentRequestError: 'ವಿನಂತಿ ಕಳುಹಿಸುವಲ್ಲಿ ದೋಷ',
    noTreatmentRecords: 'ಚಿಕಿತ್ಸಾ ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    symptomsReported: 'ವರದಿಯಾದ ಲಕ್ಷಣಗಳು',
    vetPrescription: 'ಪಶುವೈದ್ಯರ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್',
    withdrawal: 'ವಿಡ್ರಾವಲ್ ಕಾಲ',
    days: 'ದಿನಗಳು',
    mlPrototype: 'Meditrack ಎಂಎಲ್ ಮಾದರಿ',
    refresh: 'ರಿಫ್ರೆಶ್',
    addReminder: 'ರಿಮೈಂಡರ್ ಸೇರಿಸಿ',
    reminderQueued: 'ರಿಮೈಂಡರ್ ಸೇರಿಸಲಾಗಿದೆ',
    copied: 'ಕಾಪಿ ಆಯಿತು',
    copyInsight: 'ಇನ್‌ಸೈಟ್ ಕಾಪಿ ಮಾಡಿ',
    adherence: 'ಔಷಧ ಪಾಲನೆ',
    dosesTaken: '{taken}/{total} ಡೋಸ್ ತೆಗೆದುಕೊಂಡಿವೆ',
    healthScore: 'ಆರೋಗ್ಯ ಅಂಕ',
    futureMissRisk: 'ಭವಿಷ್ಯದಲ್ಲಿ ಡೋಸ್ ತಪ್ಪುವ ಅಪಾಯ',
    trend: 'ಪ್ರವೃತ್ತಿ',
    trendChange: '{delta}% ಬದಲಾವಣೆ',
    trendAnalysis: 'ಪ್ರವೃತ್ತಿ ವಿಶ್ಲೇಷಣೆ',
    adherenceOverTime: 'ಕಾಲಕ್ರಮದಲ್ಲಿ ಔಷಧ ಪಾಲನೆ',
    patternDetection: 'ಮಾದರಿ ಗುರುತಿಕೆ',
    mostMissedTime: 'ಹೆಚ್ಚಾಗಿ ತಪ್ಪಿದ ಸಮಯ',
    detectedCluster: 'ಗುರುತಿಸಿದ ಗುಂಪು',
    methodTimeClustering: 'ತಪ್ಪಿದ ಡೋಸ್ ಸಂಖ್ಯೆಯ ಆಧಾರದ ಮೇಲೆ ಸಮಯ-ಗುಂಪು ವಿಶ್ಲೇಷಣೆ',
    medicineWiseAnalysis: 'ಔಷಧವಾರು ವಿಶ್ಲೇಷಣೆ',
    missedOutOf: '{total} ನಲ್ಲಿ {missed} ತಪ್ಪಿವೆ',
    smartRecommendations: 'ಸ್ಮಾರ್ಟ್ ಶಿಫಾರಸುಗಳು',
    dataSource: 'ಡೇಟಾ ಮೂಲ',
    demoFallbackData: 'ಡೆಮೋ ಡೇಟಾ',
    estimatedBilling: 'ಬಿಲ್ಲಿಂಗ್ ಇತಿಹಾಸದಿಂದ ಅಂದಾಜು',
    estimatedTreatment: 'ಚಿಕಿತ್ಸಾ ಇತಿಹಾಸದಿಂದ ಅಂದಾಜು',
    reportStatusHigh: 'ಹೆಚ್ಚು',
    reportStatusMedium: 'ಮಧ್ಯಮ',
    reportStatusLow: 'ಕಡಿಮೆ',
    reportStatusHealthy: 'ಆರೋಗ್ಯಕರ',
    reportStatusModerate: 'ಮಧ್ಯಮ',
    reportStatusCritical: 'ಗಂಭೀರ',
    reportStatusImproving: 'ಸುಧಾರಿಸುತ್ತಿದೆ',
    reportStatusStable: 'ಸ್ಥಿರ',
    reportStatusDeclining: 'ಕಡಿಮೆಯಾಗುತ್ತಿದೆ',
    timeMorning: 'ಬೆಳಗ್ಗೆ',
    timeAfternoon: 'ಮಧ್ಯಾಹ್ನ',
    timeNight: 'ರಾತ್ರಿ',
    aiInsight: 'ಬಳಕೆದಾರರು ಹೆಚ್ಚು {timeSlot} ಔಷಧವನ್ನು ತಪ್ಪಿಸುತ್ತಾರೆ. ಔಷಧ ಪಾಲನೆ {adherenceClass}, ಆರೋಗ್ಯ ಸ್ಥಿತಿ {healthClass}, ಮತ್ತು ಮುಂದಿನ ಡೋಸ್ ತಪ್ಪುವ ಅಪಾಯ {riskLevel}. ಪ್ರವೃತ್ತಿ {trendDirection}.',
    aiInsightWorstMedicine: ' ಹೆಚ್ಚು ಗಮನ ಬೇಕಾದ ಔಷಧ {medicine}.',
    recNight: 'ರಾತ್ರಿ ಡೋಸ್ ರಿಮೈಂಡರ್ ಅನ್ನು ಸ್ವಲ್ಪ ಮುಂಚಿತವಾಗಿ ಇಟ್ಟು, ಸಂಜೆ ಆಹಾರ ಕೊಡುವುದು ಅಥವಾ ಶೆಡ್ ಮುಚ್ಚುವುದು ಎಂಬ ಅಭ್ಯಾಸಕ್ಕೆ ಜೋಡಿಸಿ.',
    recMorning: 'ಬೆಳಗಿನ ಕೆಲಸ ಶುರುವಾಗುವ ಮೊದಲು ರಿಮೈಂಡರ್ ಇಡಿ, ಹೀಗಾಗಿ ಬ್ಯುಸಿ ಸಮಯದಲ್ಲಿ ಡೋಸ್ ತಪ್ಪುವುದಿಲ್ಲ.',
    recAfternoon: 'ಮಧ್ಯಾಹ್ನ ಡೋಸ್‌ಗಳು ತಪ್ಪುತ್ತಿರುವುದರಿಂದ ಮಧ್ಯಾಹ್ನದ ರಿಮೈಂಡರ್ ಸೇರಿಸಿ.',
    recLow: 'ಎರಡು ಹಂತದ ರಿಮೈಂಡರ್ ಬಳಸಿ: ಮೊದಲು ರೈತನಿಗೆ ಎಚ್ಚರಿಕೆ, ನಂತರ ಔಷಧ ತೆಗೆದುಕೊಂಡದ್ದು ದೃಢೀಕರಿಸಿ.',
    recMedium: 'ಚಿಕಿತ್ಸಾ ಯೋಜನೆಯನ್ನು ಮುಂದುವರಿಸಿ, ಆದರೆ ಪಾಲನೆ 85 ಶೇಕಡಕ್ಕಿಂತ ಮೇಲಾಗುವವರೆಗೆ ದಿನನಿತ್ಯದ ಚೆಕ್‌ಲಿಸ್ಟ್ ಬಳಸಿ.',
    recHigh: 'ಔಷಧ ಪಾಲನೆ ಉತ್ತಮವಾಗಿದೆ. ಪ್ರಸ್ತುತ ರೂಟೀನ್ ಮುಂದುವರಿಸಿ ಮತ್ತು ಅಚಾನಕ್ ತಪ್ಪುವ ಡೋಸ್‌ಗಳನ್ನು ಗಮನಿಸಿ.',
    recRiskHigh: 'ಮುಂದೆ ಡೋಸ್ ತಪ್ಪುವ ಸಾಧ್ಯತೆ ಹೆಚ್ಚು, ಆದ್ದರಿಂದ ಈ ಪ್ರಾಣಿಗೆ ಫಾಲೋ-ಅಪ್ ಇಡಿ.',
    recDeclining: 'ಪಾಲನೆ ಕಡಿಮೆಯಾಗುತ್ತಿದೆ, ಆದ್ದರಿಂದ ಇತ್ತೀಚಿನ ಚಿಕಿತ್ಸಾ ದಿನಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    recWorstMedicine: '{medicine} ಮೇಲೆ ಹೆಚ್ಚು ಗಮನ ನೀಡಿ, ಏಕೆಂದರೆ ಇದರ ಡೋಸ್‌ಗಳು ಹೆಚ್ಚು ತಪ್ಪಿವೆ.',
    recVetApproval: 'ಪಶುವೈದ್ಯರ ಅನುಮತಿ ಇಲ್ಲದೆ ಡೋಸ್ ಬದಲಾಯಿಸಬೇಡಿ.',
  },
  ml: {
    theme: 'തീം',
    light: 'ലൈറ്റ്',
    dark: 'ഡാർക്ക്',
    language: 'ഭാഷ',
    signOut: 'സൈൻ ഔട്ട്',
    loginTitle: 'വീണ്ടും സ്വാഗതം',
    loginSubtitle: 'നിങ്ങളുടെ Meditrack ഡാഷ്ബോർഡിൽ പ്രവേശിക്കാൻ വിവരങ്ങൾ നൽകുക.',
    phoneNumber: 'ഫോൺ നമ്പർ',
    password: 'പാസ്‌വേഡ്',
    enterPassword: 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക',
    signIn: 'സുരക്ഷിതമായി സൈൻ ഇൻ',
    signingIn: 'സൈൻ ഇൻ ചെയ്യുന്നു...',
    noAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    signupHere: 'ഇവിടെ സൈൻ അപ്പ് ചെയ്യുക',
    demoShortcuts: 'ഡെമോ ലോഗിൻ ഷോർട്ട്കട്ടുകൾ',
    createAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    joinNetwork: 'നെറ്റ്‌വർക്കിൽ ചേരുക',
    registerCopy: 'മൃഗാരോഗ്യം, പ്രിസ്ക്രിപ്ഷൻ, AI മരുന്ന് പാലന വിവരങ്ങൾ, AMU ഡാറ്റ എന്നിവ കൈകാര്യം ചെയ്യാൻ അക്കൗണ്ട് സൃഷ്ടിക്കുക.',
    fullName: 'പൂർണ്ണ പേര്',
    city: 'നഗരം/ജില്ല',
    role: 'പങ്ക് തിരഞ്ഞെടുക്കുക',
    createMeditrackAccount: 'Meditrack അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    creatingAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു...',
    alreadyAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    loginHere: 'ഇവിടെ ലോഗിൻ ചെയ്യുക',
    myMedicineAdherenceReport: 'എന്റെ മരുന്ന് പാലന റിപ്പോർട്ട്',
    chooseFromHerd: '-- നിങ്ങളുടെ കൂട്ടത്തിൽ നിന്ന് തിരഞ്ഞെടുക്കുക --',
    describeSymptoms: 'ലക്ഷണങ്ങൾ എഴുതുക',
    symptomsPlaceholder: 'ഉദാ., ഭക്ഷണം നിർത്തി, ഉയർന്ന പനി...',
    sendingAlert: 'അലർട്ട് അയയ്ക്കുന്നു...',
    treatmentRequestSuccess: 'ചികിത്സ അഭ്യർത്ഥന അടുത്തുള്ള ഡോക്ടർമാർക്ക് അയച്ചു!',
    treatmentRequestError: 'അഭ്യർത്ഥന അയയ്ക്കുന്നതിൽ പിഴവ്',
    noTreatmentRecords: 'ചികിത്സാ രേഖകൾ കണ്ടെത്തിയില്ല.',
    symptomsReported: 'റിപ്പോർട്ട് ചെയ്ത ലക്ഷണങ്ങൾ',
    vetPrescription: 'വെറ്റ് ഡോക്ടറുടെ പ്രിസ്ക്രിപ്ഷൻ',
    withdrawal: 'വിടവാങ്ങൽ കാലം',
    days: 'ദിവസങ്ങൾ',
    mlPrototype: 'Meditrack എംഎൽ മാതൃക',
    refresh: 'റിഫ്രെഷ്',
    addReminder: 'റിമൈണ്ടർ ചേർക്കുക',
    reminderQueued: 'റിമൈണ്ടർ ചേർത്തു',
    copied: 'കോപ്പി ചെയ്തു',
    copyInsight: 'ഇൻസൈറ്റ് കോപ്പി ചെയ്യുക',
    adherence: 'മരുന്ന് പാലനം',
    dosesTaken: '{taken}/{total} ഡോസുകൾ എടുത്തു',
    healthScore: 'ആരോഗ്യ സ്കോർ',
    futureMissRisk: 'ഭാവിയിൽ ഡോസ് മിസ് ചെയ്യുന്ന അപകടം',
    trend: 'പ്രവണത',
    trendChange: '{delta}% മാറ്റം',
    trendAnalysis: 'പ്രവണത വിശകലനം',
    adherenceOverTime: 'കാലക്രമത്തിൽ മരുന്ന് പാലനം',
    patternDetection: 'പാറ്റേൺ കണ്ടെത്തൽ',
    mostMissedTime: 'ഏറ്റവും കൂടുതൽ മിസ് ചെയ്ത സമയം',
    detectedCluster: 'കണ്ടെത്തിയ സംഘം',
    methodTimeClustering: 'മിസ് ചെയ്ത ഡോസ് എണ്ണത്തിന്റെ അടിസ്ഥാനത്തിൽ സമയ-സംഘ വിശകലനം',
    medicineWiseAnalysis: 'മരുന്ന് പ്രകാരമുള്ള വിശകലനം',
    missedOutOf: '{total} ൽ {missed} മിസ് ചെയ്തു',
    smartRecommendations: 'സ്മാർട്ട് ശുപാർശകൾ',
    dataSource: 'ഡാറ്റ ഉറവിടം',
    demoFallbackData: 'ഡെമോ ഡാറ്റ',
    estimatedBilling: 'ബില്ലിംഗ് ചരിത്രത്തിൽ നിന്ന് കണക്കാക്കിയതു',
    estimatedTreatment: 'ചികിത്സാ ചരിത്രത്തിൽ നിന്ന് കണക്കാക്കിയതു',
    reportStatusHigh: 'ഉയർന്ന',
    reportStatusMedium: 'മധ്യം',
    reportStatusLow: 'കുറവ്',
    reportStatusHealthy: 'ആരോഗ്യകരം',
    reportStatusModerate: 'മിതമായ',
    reportStatusCritical: 'ഗുരുതരം',
    reportStatusImproving: 'മെച്ചപ്പെടുന്നു',
    reportStatusStable: 'സ്ഥിരം',
    reportStatusDeclining: 'കുറയുന്നു',
    timeMorning: 'രാവിലെ',
    timeAfternoon: 'ഉച്ചയ്ക്ക്',
    timeNight: 'രാത്രി',
    aiInsight: 'ഉപയോക്താവ് കൂടുതലായി {timeSlot} മരുന്ന് മിസ് ചെയ്യുന്നു. മരുന്ന് പാലനം {adherenceClass}, ആരോഗ്യ നില {healthClass}, ഭാവിയിലെ ഡോസ് മിസ് അപകടം {riskLevel}. പ്രവണത {trendDirection}.',
    aiInsightWorstMedicine: ' കൂടുതൽ ശ്രദ്ധ വേേണ്ട മരുന്ന് {medicine}.',
    recNight: 'രാത്രി ഡോസ് റിമൈണ്ടർ കുറച്ച് നേരത്തെ വെച്ച്, വൈകുന്നേരത്തെ ഭക്ഷണം നൽകൽ അല്ലെങ്കിൽ ഷെഡ് അടയ്ക്കൽ പോലുള്ള പതിവുമായി ബന്ധിപ്പിക്കുക.',
    recMorning: 'രാവിലെ ഫാം ജോലി തുടങ്ങുന്നതിന് മുമ്പ് റിമൈണ്ടർ വെക്കുക, അപ്പോൾ തിരക്കേറിയ സമയത്ത് ഡോസ് മിസ് ആവില്ല.',
    recAfternoon: 'ഉച്ചയ്ക്ക് ഡോസ് മിസ് ചെയ്യുന്നത് കൂടുന്നതിനാൽ ഉച്ചതിരിഞ്ഞ് റിമൈണ്ടർ ചേർക്കുക.',
    recLow: 'രണ്ട് ഘട്ട റിമൈണ്ടർ ഉപയോഗിക്കുക: ആദ്യം കർഷകനെ അലർട്ട് ചെയ്യുക, പിന്നെ മരുന്ന് എടുത്തതായി സ്ഥിരീകരിക്കുക.',
    recMedium: 'ചികിത്സാ പദ്ധതി തുടരുക, എന്നാൽ പാലനം 85 ശതമാനത്തിന് മുകളിൽ എത്തും വരെ ദൈനംദിന ചെക്ക്ലിസ്റ്റ് ഉപയോഗിക്കുക.',
    recHigh: 'മരുന്ന് പാലനം നല്ലതാണ്. നിലവിലെ രീതി തുടരുക, അപ്രതീക്ഷിതമായി ഡോസ് മിസ് ആകുന്നുണ്ടോ ശ്രദ്ധിക്കുക.',
    recRiskHigh: 'ഭാവിയിൽ ഡോസ് മിസ് ചെയ്യാനുള്ള സാധ്യത കൂടുതലായതിനാൽ ഈ മൃഗത്തിന് ഫോളോ-അപ്പ് നൽകുക.',
    recDeclining: 'പാലനം കുറയുന്നു, അതിനാൽ അടുത്തകാലത്തെ ചികിത്സാ ദിവസങ്ങൾ പരിശോധിക്കുക.',
    recWorstMedicine: '{medicine} ന് കൂടുതൽ ശ്രദ്ധ കൊടുക്കുക, കാരണം ഇതിന്റെ ഡോസ് കൂടുതലായി മിസ് ചെയ്തു.',
    recVetApproval: 'വെറ്റ് ഡോക്ടറുടെ അനുമതിയില്ലാതെ ഡോസ് മാറ്റരുത്.',
  },
  pa: {
    theme: 'ਥੀਮ',
    light: 'ਲਾਈਟ',
    dark: 'ਡਾਰਕ',
    language: 'ਭਾਸ਼ਾ',
    signOut: 'ਸਾਈਨ ਆਉਟ',
    loginTitle: 'ਮੁੜ ਸੁਆਗਤ ਹੈ',
    loginSubtitle: 'ਆਪਣੇ Meditrack ਡੈਸ਼ਬੋਰਡ ਵਿੱਚ ਜਾਣ ਲਈ ਵੇਰਵੇ ਭਰੋ।',
    phoneNumber: 'ਫੋਨ ਨੰਬਰ',
    password: 'ਪਾਸਵਰਡ',
    enterPassword: 'ਆਪਣਾ ਪਾਸਵਰਡ ਭਰੋ',
    signIn: 'ਸੁਰੱਖਿਅਤ ਸਾਈਨ ਇਨ',
    signingIn: 'ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...',
    noAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    signupHere: 'ਇੱਥੇ ਸਾਈਨ ਅਪ ਕਰੋ',
    demoShortcuts: 'ਡੇਮੋ ਲਾਗਇਨ ਸ਼ਾਰਟਕੱਟ',
    createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    joinNetwork: 'ਨੈੱਟਵਰਕ ਨਾਲ ਜੁੜੋ',
    fullName: 'ਪੂਰਾ ਨਾਮ',
    city: 'ਸ਼ਹਿਰ/ਜ਼ਿਲ੍ਹਾ',
    role: 'ਭੂਮਿਕਾ ਚੁਣੋ',
    createMeditrackAccount: 'Meditrack ਖਾਤਾ ਬਣਾਓ',
    creatingAccount: 'ਖਾਤਾ ਬਣ ਰਿਹਾ ਹੈ...',
    alreadyAccount: 'ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?',
    loginHere: 'ਇੱਥੇ ਲਾਗਇਨ ਕਰੋ',
    myMedicineAdherenceReport: 'ਮੇਰੀ ਦਵਾਈ ਪਾਲਣਾ ਰਿਪੋਰਟ',
    mlPrototype: 'Meditrack ਐਮਐਲ ਪ੍ਰੋਟੋਟਾਇਪ',
    refresh: 'ਰਿਫ੍ਰੈਸ਼',
    addReminder: 'ਰਿਮਾਈਂਡਰ ਜੋੜੋ',
    copyInsight: 'ਇਨਸਾਈਟ ਕਾਪੀ ਕਰੋ',
    adherence: 'ਦਵਾਈ ਪਾਲਣਾ',
    dosesTaken: '{taken}/{total} ਡੋਜ਼ ਲਏ',
    healthScore: 'ਸਿਹਤ ਸਕੋਰ',
    futureMissRisk: 'ਭਵਿੱਖ ਵਿੱਚ ਡੋਜ਼ ਛੁੱਟਣ ਦਾ ਖ਼ਤਰਾ',
    trend: 'ਰੁਝਾਨ',
    trendAnalysis: 'ਰੁਝਾਨ ਵਿਸ਼ਲੇਸ਼ਣ',
    patternDetection: 'ਪੈਟਰਨ ਪਛਾਣ',
    mostMissedTime: 'ਸਭ ਤੋਂ ਵੱਧ ਛੁੱਟਿਆ ਸਮਾਂ',
    medicineWiseAnalysis: 'ਦਵਾਈ ਅਨੁਸਾਰ ਵਿਸ਼ਲੇਸ਼ਣ',
    smartRecommendations: 'ਸਮਾਰਟ ਸਿਫ਼ਾਰਸ਼ਾਂ',
    dataSource: 'ਡਾਟਾ ਸਰੋਤ',
    reportStatusHigh: 'ਉੱਚ',
    reportStatusMedium: 'ਦਰਮਿਆਨਾ',
    reportStatusLow: 'ਘੱਟ',
    reportStatusHealthy: 'ਸਿਹਤਮੰਦ',
    reportStatusCritical: 'ਗੰਭੀਰ',
    reportStatusImproving: 'ਸੁਧਰ ਰਿਹਾ ਹੈ',
    reportStatusStable: 'ਸਥਿਰ',
    reportStatusDeclining: 'ਘਟ ਰਿਹਾ ਹੈ',
    timeMorning: 'ਸਵੇਰ',
    timeAfternoon: 'ਦੁਪਹਿਰ',
    timeNight: 'ਰਾਤ',
  },
  ur: {
    theme: 'تھیم',
    light: 'لائٹ',
    dark: 'ڈارک',
    language: 'زبان',
    signOut: 'سائن آؤٹ',
    loginTitle: 'واپس خوش آمدید',
    loginSubtitle: 'اپنے Meditrack ڈیش بورڈ تک رسائی کے لیے معلومات درج کریں۔',
    phoneNumber: 'فون نمبر',
    password: 'پاس ورڈ',
    enterPassword: 'اپنا پاس ورڈ درج کریں',
    signIn: 'محفوظ سائن اِن',
    signingIn: 'سائن اِن ہو رہا ہے...',
    noAccount: 'اکاؤنٹ نہیں ہے؟',
    signupHere: 'یہاں سائن اَپ کریں',
    demoShortcuts: 'ڈیمو لاگ اِن شارٹ کٹ',
    createAccount: 'اکاؤنٹ بنائیں',
    joinNetwork: 'نیٹ ورک میں شامل ہوں',
    fullName: 'پورا نام',
    city: 'شہر/ضلع',
    role: 'کردار منتخب کریں',
    createMeditrackAccount: 'Meditrack اکاؤنٹ بنائیں',
    creatingAccount: 'اکاؤنٹ بن رہا ہے...',
    alreadyAccount: 'پہلے سے اکاؤنٹ ہے؟',
    loginHere: 'یہاں لاگ اِن کریں',
    myMedicineAdherenceReport: 'میری دوا پابندی رپورٹ',
    mlPrototype: 'Meditrack ایم ایل پروٹوٹائپ',
    refresh: 'ریفریش',
    addReminder: 'ریمائنڈر شامل کریں',
    copyInsight: 'انسائٹ کاپی کریں',
    adherence: 'دوا کی پابندی',
    dosesTaken: '{taken}/{total} خوراکیں لی گئیں',
    healthScore: 'صحت اسکور',
    futureMissRisk: 'آئندہ خوراک چھوٹنے کا خطرہ',
    trend: 'رجحان',
    trendAnalysis: 'رجحان تجزیہ',
    patternDetection: 'پیٹرن شناخت',
    mostMissedTime: 'سب سے زیادہ چھوٹا وقت',
    medicineWiseAnalysis: 'دوا کے حساب سے تجزیہ',
    smartRecommendations: 'سمارٹ تجاویز',
    dataSource: 'ڈیٹا ذریعہ',
    reportStatusHigh: 'زیادہ',
    reportStatusMedium: 'درمیانہ',
    reportStatusLow: 'کم',
    reportStatusHealthy: 'صحت مند',
    reportStatusCritical: 'سنگین',
    reportStatusImproving: 'بہتر ہو رہا ہے',
    reportStatusStable: 'مستحکم',
    reportStatusDeclining: 'کم ہو رہا ہے',
    timeMorning: 'صبح',
    timeAfternoon: 'دوپہر',
    timeNight: 'رات',
  },
  od: {
    theme: 'ଥିମ୍',
    light: 'ଲାଇଟ୍',
    dark: 'ଡାର୍କ',
    language: 'ଭାଷା',
    signOut: 'ସାଇନ୍ ଆଉଟ୍',
    loginTitle: 'ପୁଣି ସ୍ୱାଗତ',
    loginSubtitle: 'ଆପଣଙ୍କ Meditrack ଡ୍ୟାଶବୋର୍ଡକୁ ଯିବା ପାଇଁ ବିବରଣୀ ଭରନ୍ତୁ।',
    phoneNumber: 'ଫୋନ୍ ନମ୍ବର',
    password: 'ପାସୱାର୍ଡ',
    enterPassword: 'ଆପଣଙ୍କ ପାସୱାର୍ଡ ଭରନ୍ତୁ',
    signIn: 'ସୁରକ୍ଷିତ ସାଇନ୍ ଇନ୍',
    signingIn: 'ସାଇନ୍ ଇନ୍ ହେଉଛି...',
    noAccount: 'ଖାତା ନାହିଁ?',
    signupHere: 'ଏଠାରେ ସାଇନ୍ ଅପ୍ କରନ୍ତୁ',
    demoShortcuts: 'ଡେମୋ ଲଗଇନ୍ ଶର୍ଟକଟ୍',
    createAccount: 'ଖାତା ତିଆରି କରନ୍ତୁ',
    joinNetwork: 'ନେଟୱର୍କରେ ଯୋଗଦିଅନ୍ତୁ',
    fullName: 'ପୂରା ନାମ',
    city: 'ସହର/ଜିଲ୍ଲା',
    role: 'ଭୂମିକା ବାଛନ୍ତୁ',
    createMeditrackAccount: 'Meditrack ଖାତା ତିଆରି କରନ୍ତୁ',
    creatingAccount: 'ଖାତା ତିଆରି ହେଉଛି...',
    alreadyAccount: 'ପୂର୍ବରୁ ଖାତା ଅଛି?',
    loginHere: 'ଏଠାରେ ଲଗଇନ୍ କରନ୍ତୁ',
    myMedicineAdherenceReport: 'ମୋ ଔଷଧ ପାଳନ ରିପୋର୍ଟ',
    mlPrototype: 'Meditrack ଏମଏଲ ପ୍ରୋଟୋଟାଇପ',
    refresh: 'ରିଫ୍ରେଶ୍',
    addReminder: 'ରିମାଇଣ୍ଡର ଯୋଡନ୍ତୁ',
    copyInsight: 'ଇନସାଇଟ୍ କପି କରନ୍ତୁ',
    adherence: 'ଔଷଧ ପାଳନ',
    dosesTaken: '{taken}/{total} ଡୋଜ୍ ନିଆଗଲା',
    healthScore: 'ସ୍ୱାସ୍ଥ୍ୟ ସ୍କୋର',
    futureMissRisk: 'ଭବିଷ୍ୟତରେ ଡୋଜ୍ ଛୁଟିବାର ଝୁମ୍ପ',
    trend: 'ପ୍ରବୃତ୍ତି',
    trendAnalysis: 'ପ୍ରବୃତ୍ତି ବିଶ୍ଳେଷଣ',
    patternDetection: 'ପ୍ୟାଟର୍ନ ଚିହ୍ନଟ',
    mostMissedTime: 'ସର୍ବାଧିକ ଛୁଟିଥିବା ସମୟ',
    medicineWiseAnalysis: 'ଔଷଧ ଅନୁସାରେ ବିଶ୍ଳେଷଣ',
    smartRecommendations: 'ସ୍ମାର୍ଟ ପରାମର୍ଶ',
    dataSource: 'ଡେଟା ଉତ୍ସ',
    reportStatusHigh: 'ଉଚ୍ଚ',
    reportStatusMedium: 'ମଧ୍ୟମ',
    reportStatusLow: 'କମ୍',
    reportStatusHealthy: 'ସୁସ୍ଥ',
    reportStatusCritical: 'ଗୁରୁତର',
    reportStatusImproving: 'ସୁଧାରୁଛି',
    reportStatusStable: 'ସ୍ଥିର',
    reportStatusDeclining: 'କମୁଛି',
    timeMorning: 'ସକାଳ',
    timeAfternoon: 'ଦୁପର',
    timeNight: 'ରାତି',
  },
  as: {
    theme: 'থীম',
    light: 'লাইট',
    dark: 'ডাৰ্ক',
    language: 'ভাষা',
    signOut: 'ছাইন আউট',
    loginTitle: 'আকৌ স্বাগতম',
    loginSubtitle: 'আপোনাৰ Meditrack ডেশ্বব’ৰ্ডলৈ যাবলৈ তথ্য ভৰক।',
    phoneNumber: 'ফোন নম্বৰ',
    password: 'পাছৱৰ্ড',
    enterPassword: 'আপোনাৰ পাছৱৰ্ড ভৰক',
    signIn: 'নিৰাপদে ছাইন ইন',
    signingIn: 'ছাইন ইন হৈ আছে...',
    noAccount: 'একাউণ্ট নাই?',
    signupHere: 'ইয়াত ছাইন আপ কৰক',
    demoShortcuts: 'ডেমো লগইন শ্বৰ্টকাট',
    createAccount: 'একাউণ্ট সৃষ্টি কৰক',
    joinNetwork: 'নেটৱৰ্কত যোগ দিয়ক',
    fullName: 'সম্পূৰ্ণ নাম',
    city: 'চহৰ/জিলা',
    role: 'ভূমিকা বাছক',
    createMeditrackAccount: 'Meditrack একাউণ্ট সৃষ্টি কৰক',
    creatingAccount: 'একাউণ্ট সৃষ্টি হৈ আছে...',
    alreadyAccount: 'আগতে একাউণ্ট আছে?',
    loginHere: 'ইয়াত লগইন কৰক',
    myMedicineAdherenceReport: 'মোৰ ঔষধ পালন প্ৰতিবেদন',
    mlPrototype: 'Meditrack এমএল প্ৰোটোটাইপ',
    refresh: 'ৰিফ্ৰেশ',
    addReminder: 'ৰিমাইণ্ডাৰ যোগ কৰক',
    copyInsight: 'ইনসাইট কপি কৰক',
    adherence: 'ঔষধ পালন',
    dosesTaken: '{taken}/{total} ডোজ লোৱা হৈছে',
    healthScore: 'স্বাস্থ্য স্কোৰ',
    futureMissRisk: 'ভৱিষ্যতে ডোজ মিছ হোৱাৰ ঝুঁকি',
    trend: 'প্ৰৱণতা',
    trendAnalysis: 'প্ৰৱণতা বিশ্লেষণ',
    patternDetection: 'পেটাৰ্ণ চিনাক্তকৰণ',
    mostMissedTime: 'সৰ্বাধিক মিছ হোৱা সময়',
    medicineWiseAnalysis: 'ঔষধ অনুসৰি বিশ্লেষণ',
    smartRecommendations: 'স্মাৰ্ট পৰামৰ্শ',
    dataSource: 'ডেটা উৎস',
    reportStatusHigh: 'উচ্চ',
    reportStatusMedium: 'মধ্যম',
    reportStatusLow: 'কম',
    reportStatusHealthy: 'সুস্থ',
    reportStatusCritical: 'গম্ভীৰ',
    reportStatusImproving: 'উন্নত হৈছে',
    reportStatusStable: 'স্থিতিশীল',
    reportStatusDeclining: 'কমিছে',
    timeMorning: 'পুৱা',
    timeAfternoon: 'দুপৰীয়া',
    timeNight: 'ৰাতি',
  },
};

Object.entries(extraRegionalLanguages).forEach(([code, values]) => {
  translations[code] = {
    ...translations.hi,
    ...values,
    ...extraRegionalUiText[code],
  };
});

const languageOptions = Object.entries(translations).map(([code, values]) => ({
  code,
  label: values.languageName,
}));

const AppSettingsContext = createContext(null);

export const AppSettingsProvider = ({ children }) => {
  const [theme, setTheme] = useState(() => localStorage.getItem('meditrack-theme') || 'light');
  const [language, setLanguage] = useState(() => localStorage.getItem('meditrack-language') || 'en');

  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    localStorage.setItem('meditrack-theme', theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ur' ? 'rtl' : 'ltr';
    localStorage.setItem('meditrack-language', language);
  }, [language]);

  const value = useMemo(() => ({
    theme,
    language,
    languages: languageOptions,
    setLanguage,
    toggleTheme: () => setTheme((current) => current === 'dark' ? 'light' : 'dark'),
    t: (key) => translations[language]?.[key] || translations.en[key] || key,
  }), [language, theme]);

  return (
    <AppSettingsContext.Provider value={value}>
      {children}
    </AppSettingsContext.Provider>
  );
};

export const useAppSettings = () => {
  const context = useContext(AppSettingsContext);
  if (!context) {
    throw new Error('useAppSettings must be used inside AppSettingsProvider');
  }
  return context;
};
